import { nextOf } from '../systems.js';
/* Blocks shared by both RIO alignment procedures.
   Sections 4 and 5 of Part 4 differ only in the middle: ashore you type the
   present position into the CAP, on the boat CAINS hands it across. */

export const RIO_PRE = [
{g:'1 · RIO Pre-Align', t:'ICS switch — <b>HOT MIC</b>',
 tgt:'rioIcs', view:'rioL', done:s=>s.sw.rioIcs==='hot'},
{g:'1 · RIO Pre-Align', t:'Verify <b>ground power</b> is connected',
 note:'The WCS cannot run without it.', tgt:'comms:ground', done:s=>s.power},
{g:'1 · RIO Pre-Align', t:'Wait for the pilot — <b>both engines running</b> and <b>AIR SOURCE BOTH ENG</b>',
 note:'The INS needs the WCS, the WCS needs ECS cooling air, and that needs both engines plus bleed air selected. Listen for his calls.',
 tgt:'scTid_rioC', view:'rioC', done:s=>s.eng.L.n2>55&&s.eng.R.n2>55&&s.sw.airSource==='both'},
{g:'1 · RIO Pre-Align', t:'Liquid Cooling — <b>AWG-9 / AIM-54</b>, forward',
 note:'Three positions. Starts the AWG-9 cooling — the third of the three conditions the WCS needs. Leave it OFF and you get an AWG-9 COND advisory.',
 note:'Forward is AWG-9/AIM-54, aft is AWG-9 alone. It will not stop the radar working either way — the wrong position just makes an overheat casualty in the AWG-9 or the missiles a matter of time.', tgt:'liquidCool', view:'rioL', done:s=>s.sw.liquidCool==='awg9aim54'},
{g:'1 · RIO Pre-Align', t:'WCS switch — <b>STANDBY</b> (middle)',
 note:'On the Right Console tab, though the HCU panel it sits on is really down by your left knee.',
 tgt:'wcsMode', view:'rioR', done:s=>s.sw.wcsMode==='stby'||s.sw.wcsMode==='xmt'},
{g:'1 · RIO Pre-Align', t:'Wait ~<b>30 seconds</b> for the TID and DDD to power on',
 note:'NAV COMP and AWG-9 COND may show while the INS is still degraded before alignment — ignore them until it completes.',
 tgt:'scTid_rioC', view:'rioC', done:s=>s.rio.wcsUp},
]

export const RIO_POST = [
{g:'4 · RIO Post-Align', t:'RIO Oxygen switch — <b>ON</b>',
 tgt:'rioOxygen', view:'rioL', done:s=>s.sw.rioOxygen==='on'},
{g:'4 · RIO Post-Align', t:'RIO ejection seat — <b>ARMED</b>, canopy <b>CLOSED</b>',
 note:'LSHIFT+E and LCTRL+C in the sim.',
 tgt:s=>nextOf(s,[['ejectSeat','armed'],['canopy','closed']]), done:s=>s.sw.ejectSeat==='armed'&&s.sw.canopy==='closed'},
{g:'4 · RIO Post-Align', t:'V/UHF radio function selector — <b>T/R +G</b>',
 tgt:'vuhfFunc', view:'rioL', done:s=>s.sw.vuhfFunc==='trg'},
{g:'4 · RIO Post-Align', t:'RIO TACAN function selector — <b>T/R</b>',
 tgt:'rioTacanFunc', view:'rioL', done:s=>s.sw.rioTacanFunc==='tr'},
{g:'4 · RIO Post-Align', t:'RIO standby ADI — <b>erect the gyro</b>',
 note:'At least two minutes before takeoff.',
 tgt:'rioStbyAdi', view:'rioC', done:s=>s.sw.rioStbyAdi==='erect'},
{g:'4 · RIO Post-Align', t:'IR / TV (TCS) power — <b>STANDBY</b>',
 note:'It runs its BIT and warm-up either way; the position only decides whether it goes active once it can.',
 tgt:'irtvPower', view:'rioR', done:s=>s.sw.irtvPower!=='off'},
{g:'4 · RIO Post-Align', t:'AN/ALR-67 RWR power — <b>ON</b>',
 note:'It warms up and starts showing detected signals on the ground — you do not have to be airborne.',
 tgt:'alr67Power', view:'rioR', done:s=>s.sw.alr67Power==='on'},
{g:'4 · RIO Post-Align', t:'AN/ALQ-126 DECM jammer mode — <b>STANDBY</b>',
 tgt:'decmMode', view:'rioR', done:s=>s.sw.decmMode==='stby'},
{g:'4 · RIO Post-Align', t:'Open the kneeboard, page to <b>TACTICAL DATALINK SYSTEMS</b>',
 tgt:'kb:datalink', done:s=>s.kb.open&&s.kb.page===1},
{g:'4 · RIO Post-Align', t:'Datalink power — <b>ON</b> (Link 4A), mode — <b>TAC</b>',
 note:'ON is the AWACS and carrier link, up to 8 tracks. AUX is Link 4C, F-14 to F-14 only, 4 tracks plus your wingmen. Datalink contacts fill the bottom half of the symbol; your own radar fills the top.',
 tgt:s=>nextOf(s,[['dlPower','on'],['dlModeSw','tac']]), ctx:['dlModeSw'], view:'rioR', done:s=>s.sw.dlPower==='on'&&s.sw.dlModeSw==='tac'},
{g:'4 · RIO Post-Align', t:'Datalink reply — <b>NORM</b>, and set your <b>ADDRESS</b>',
 note:'In CANC you send nothing back. Every jet in the flight needs its own address — 01 lead, 02 wing, 03 element lead, 04 his wing.',
 tgt:'dlReply', view:'rioR', done:s=>s.sw.dlReply==='norm'},
{g:'4 · RIO Post-Align', t:'Frequency wheels — <b>09.2</b> for the E-2C (309.20)',
 note:'Recommended rather than mandatory, per the guide.',
 tgt:'dlFreq', view:'rioR', done:s=>s.sw.dlFreq==='092'},
{g:'4 · RIO Post-Align', t:'Close the kneeboard',
 tgt:'kb:datalink', done:s=>!s.kb.open},
{g:'4 · RIO Post-Align', t:'IFF Mode 4 power — <b>ON</b>',
 tgt:'iffMode4', view:'rioR', done:s=>s.sw.iffMode4==='on'},
{g:'4 · RIO Post-Align', t:'AN/ALE-39 PWR / MODE — <b>MAN</b> or <b>AUTO (CHAFF)</b>, as required',
 tgt:'ale39Mode', view:'rioR', done:s=>s.sw.ale39Mode!=='off'},
{g:'4 · RIO Post-Align', t:'Flare mode — <b>PILOT</b>',
 note:'Lets the front-seater punch flares with the DLC button.',
 tgt:'flareMode', view:'rioR', done:s=>s.sw.flareMode==='pilot'},
{g:'4 · RIO Post-Align', t:'WCS — leave at <b>STANDBY</b>. <b>Ready to taxi.</b>',
 note:'Weight on Wheels inhibits transmission anyway, and leaving it in STANDBY is the safe call in case that switch fails. Go to XMT once airborne.',
 tgt:'wcsMode', view:'rioR', done:s=>s.sw.wcsMode==='stby'||s.sw.wcsMode==='xmt'},
{g:'5 · Taxi and After', t:'IR / TV (TCS) — <b>ON</b> as required',
 note:'Fine to do on the ground once you are rolling.',
 tgt:'irtvPower', view:'rioR', done:s=>s.sw.irtvPower==='on'},
]
