/* F-14B · PILOT START-UP
   Chuck's DCS F-14B guide, Part 4 sections 1-3 (62 numbered steps),
   plus the oversweep exit from Part 5 steps 8-9.
   done(s) is evaluated every frame; a step ticks itself off when the
   aircraft actually reaches that state. Steps are gated in order. */

export const meta = { id:'pilot-start', crew:'pilot', name:'Cold start', view:'front' };

export const steps = [
/* ---------------- 1. PILOT PRE-START ---------------- */
{n:1,  g:'1 · Pilot Pre-Start', t:'Parking Brake — <b>ENGAGED</b> (pull aft)',
 note:'The black-and-yellow striped pull handle in the bottom left corner of the front panel.',
 tgt:'parkBrake', done:s=>s.sw.parkBrake==='set'},
{n:2,  g:'1 · Pilot Pre-Start', t:'Ground crew — connect <b>Ground Electric Power</b>',
 note:'\\ → F8 Ground Crew → F2 Electric Power → F1 ON. The Tomcat has no battery and no APU — it is dead until external power or a generator feeds it.',
 tgt:'comms:ground', done:s=>s.gpu},
{n:3,  g:'1 · Pilot Pre-Start', t:'Ground crew — connect <b>compressed air supply</b>',
 note:'\\ → F8 → F5 Ground Air Supply → F1. The F110 has a pneumatic starter, so no air cart means no start.',
 tgt:'comms:ground', done:s=>s.airCart},
{n:4,  g:'1 · Pilot Pre-Start', t:'ICS switch — <b>HOT MIC</b>',
 tgt:'ics', done:s=>s.sw.ics==='hot'},
{n:5,  g:'1 · Pilot Pre-Start', t:'Jester — request <b>STARTUP</b>',
 note:'Press A for the Jester menu, then LCTRL+3.',
 tgt:'comms:jester', done:s=>s.jester.startupRequested},
{n:6,  g:'1 · Pilot Pre-Start', t:'Jester — answer the comm check <b>LOUD AND CLEAR</b>',
 note:'A → LCTRL+4, once he calls for the check.',
 tgt:'comms:jester', done:s=>s.jester.commCheckDone},
{n:7,  g:'1 · Pilot Pre-Start', t:'Ejection seat — <b>ARMED</b> (handle down)',
 note:'LSHIFT+E in the sim. Jester closes the canopy as soon as the seat is armed.',
 tgt:'ejectSeat', done:s=>s.sw.ejectSeat==='armed'},
{n:8,  g:'1 · Pilot Pre-Start', t:'Canopy — <b>CLOSED</b>',
 note:'Jester does this for you. With a human RIO it is LCTRL+C.',
 tgt:'canopy', done:s=>s.sw.canopy==='closed'},
{n:9,  g:'1 · Pilot Pre-Start', t:'Oxygen switch — <b>ON</b> (forward)',
 tgt:'oxygen', done:s=>s.sw.oxygen==='on'},
{n:10, g:'1 · Pilot Pre-Start', t:'Verify Emergency Wing Sweep handle — <b>OVERSWEEP</b> (aft)',
 note:'The jet is parked in oversweep at 68° so it does not clip anyone on a packed deck.',
 tgt:'wingSweep', done:s=>s.sw.wingSweep==='oversweep'},

/* ---------------- 2. ENGINE START ---------------- */
{n:11, g:'2 · Engine Start', t:'AIR SOURCE — <b>OFF</b>',
 note:'Bleed air has to go to the starter, not the ECS.',
 tgt:'airSource', done:s=>s.sw.airSource==='off'},
{n:12, g:'2 · Engine Start', t:'HYD TRANSFER pump — <b>SHUTOFF</b>',
 tgt:'hydTransfer', done:s=>s.sw.hydTransfer==='shutoff'},
{n:13, g:'2 · Engine Start', t:'Emergency Flight Hydraulics — <b>AUTO / LOW</b>',
 note:'Three positions: AUTO/LOW, LOW and HIGH.',
 tgt:'emergFltHyd', done:s=>s.sw.emergFltHyd==='autolow'},
{n:14, g:'2 · Engine Start', t:'L and R MASTER GEN — verify <b>NORM</b>',
 tgt:'masterGenL', done:s=>s.sw.masterGenL==='norm'&&s.sw.masterGenR==='norm'},
{n:15, g:'2 · Engine Start', t:'Engine Crank — <b>R</b> (right engine first)',
 note:'Right-click the crank switch — the L / OFF / R toggle below the INLET RAMPS switches. START VALVE lights and N2 winds up to about 20%.',
 tgt:'engCrank', done:s=>s.sw.engCrank==='right'||s.eng.R.lit},
{n:16, g:'2 · Engine Start', t:'At <b>20% N2</b> — right throttle <b>OFF → IDLE</b>',
 note:'Opens the fuel valves. Igniters fire, EGT should move within 5–15 seconds.',
 tgt:'throttleR', done:s=>s.eng.R.lit},
{n:17, g:'2 · Engine Start', t:'Monitor — oil pressure rising, TIT below <b>890 °C</b>',
 note:'A hung or hot start means throttle back to CUTOFF immediately.',
 tgt:'tapeTit', done:s=>s.eng.R.n2>45},
{n:18, g:'2 · Engine Start', t:'At ~50% N2 — crank switch springs to <b>OFF</b>, START VALVE out',
 tgt:'clStartValve', done:s=>s.eng.R.n2>52&&s.sw.engCrank==='off'},
{n:19, g:'2 · Engine Start', t:'Right engine stable — <b>R GEN</b> caution out',
 note:'62–78% RPM · ~500 °C · 950–1400 pph · nozzle 100% · oil 25–35 psi · flight hyd 3000 psi.',
 tgt:'clRGen', done:s=>s.eng.R.n2>=62&&!s.caution.rGen},
{n:20, g:'2 · Engine Start', t:'Engine Crank — <b>L</b> (left engine)',
 note:'Left-click the same crank switch this time.',
 tgt:'engCrank', done:s=>s.sw.engCrank==='left'||s.eng.L.lit},
{n:21, g:'2 · Engine Start', t:'At <b>20% N2</b> — left throttle <b>OFF → IDLE</b>',
 tgt:'throttleL', done:s=>s.eng.L.lit},
{n:22, g:'2 · Engine Start', t:'Monitor — oil pressure rising, TIT below <b>890 °C</b>',
 tgt:'tapeTit', done:s=>s.eng.L.n2>45},
{n:23, g:'2 · Engine Start', t:'At ~50% N2 — crank switch springs to <b>OFF</b>, START VALVE out',
 tgt:'clStartValve', done:s=>s.eng.L.n2>52&&s.sw.engCrank==='off'},
{n:24, g:'2 · Engine Start', t:'Left engine stable — <b>L GEN</b> caution out',
 note:'Same numbers as the right: 62–78% RPM, ~500 °C, 950–1400 pph, nozzle 100%, oil 25–35 psi.',
 tgt:'clLGen', done:s=>s.eng.L.n2>=62&&!s.caution.lGen},
{n:25, g:'2 · Engine Start', t:'HYD TRANSFER pump — <b>NORM</b>',
 tgt:'hydTransfer', done:s=>s.sw.hydTransfer==='norm'},
{n:26, g:'2 · Engine Start', t:'Verify COMBINED and FLIGHT hydraulics both <b>3000 psi</b>, no HYD PRESS caution',
 tgt:'dgHyd', done:s=>s.hydComb>2900&&s.hydFlt>2900&&!s.caution.hydPress},
{n:27, g:'2 · Engine Start', t:'AIR SOURCE — <b>BOTH ENG</b>',
 note:'The WCS needs ECS cooling air before the RIO can align the INS.',
 tgt:'airSource', done:s=>s.sw.airSource==='both'},
{n:28, g:'2 · Engine Start', t:'Ground crew — <b>disconnect</b> electrical power',
 note:'\\ → F8 → F2 → F2 OFF.',
 tgt:'comms:ground', done:s=>!s.gpu},
{n:29, g:'2 · Engine Start', t:'Ground crew — <b>disconnect</b> air supply',
 note:'\\ → F8 → F5 → F2.',
 tgt:'comms:ground', done:s=>!s.airCart},

/* ---------------- 3. POST-START ---------------- */
{n:30, g:'3 · Pilot Post-Start', t:'VDI, HUD and HSD power switches — <b>ON</b>',
 tgt:'vdiPower', view:'panel',
 done:s=>s.sw.vdiPower==='on'&&s.sw.hudPower==='on'&&s.sw.hsdPower==='on'},
{n:31, g:'3 · Pilot Post-Start', t:'HSD Mode — <b>TID</b>',
 note:'Repeats the RIO\'s Tactical Information Display so you can watch the INS align.',
 tgt:'hsdMode', view:'panel', done:s=>s.sw.hsdMode==='tid'},
{n:32, g:'3 · Pilot Post-Start', t:'INS alignment — Jester starts a <b>FINE</b> alignment on his own',
 note:'You only need the Jester menu if you want a degraded alignment. Fine takes about 8 minutes — use time compression up top. Leave the parking brake set or it will hang.',
 tgt:'scHsd', done:s=>s.ins.mode!==null},
{n:33, g:'3 · Pilot Post-Start', t:'Wait for alignment — Jester calls <b>“Ready to taxi”</b>',
 tgt:'scHsd', done:s=>s.ins.complete},
{n:34, g:'3 · Pilot Post-Start', t:'GUN RATE — as required',
 tgt:'gunRate', done:s=>s.touched.gunRate},
{n:35, g:'3 · Pilot Post-Start', t:'SW COOL — <b>OFF</b>',
 tgt:'swCool', done:s=>s.sw.swCool==='off'},
{n:36, g:'3 · Pilot Post-Start', t:'MSL PREP — <b>OFF</b>',
 tgt:'mslPrep', done:s=>s.sw.mslPrep==='off'},
{n:37, g:'3 · Pilot Post-Start', t:'Missile MODE/STP — <b>NORM</b>',
 tgt:'modeStp', done:s=>s.sw.modeStp==='norm'},
{n:38, g:'3 · Pilot Post-Start', t:'ANTI-SKID / SPOILER BK — <b>OFF</b> for the boat, <b>SPOILER BK</b> for a ground taxi',
 note:'BOTH is for takeoff and landing only. Left in BOTH during a slow taxi the brakes can drop out for 2–10 seconds as you accelerate through ~15 kt.',
 tgt:'antiSkid', view:'panel', done:s=>s.sw.antiSkid!=='both'},
{n:39, g:'3 · Pilot Post-Start', t:'Verify wing sweep <b>68°</b>, handle full aft',
 tgt:'wingSweep', done:s=>s.sweep>=67.5&&s.sw.wingSweep==='oversweep'},
{n:40, g:'3 · Pilot Post-Start', t:'AFCS SAS — <b>PITCH, ROLL, YAW ON</b>',
 tgt:'afcsPitch', view:'console',
 done:s=>s.sw.afcsPitch==='on'&&s.sw.afcsRoll==='on'&&s.sw.afcsYaw==='on'},
{n:41, g:'3 · Pilot Post-Start', t:'WING/EXT TRANS — <b>AUTO</b>',
 tgt:'wingExtTrans', view:'panel', done:s=>s.sw.wingExtTrans==='auto'},
{n:42, g:'3 · Pilot Post-Start', t:'UHF 1 function selector — <b>BOTH</b>',
 tgt:'uhfFunc', view:'console', done:s=>s.sw.uhfFunc==='both'},
{n:43, g:'3 · Pilot Post-Start', t:'TACAN function selector — <b>T/R</b>',
 tgt:'tacanFunc', view:'console', done:s=>s.sw.tacanFunc==='tr'},
{n:44, g:'3 · Pilot Post-Start', t:'ARA-63 ICLS receiver power — <b>ON</b>',
 tgt:'ara63', view:'console', done:s=>s.sw.ara63==='on'},
{n:45, g:'3 · Pilot Post-Start', t:'Radar altimeter — one click <b>clockwise</b> to start BIT',
 note:'The needle slams to maximum as it powers up, then settles at 100 ±5 ft for the test before dropping back to 0.',
 tgt:'radAltKnob', view:'panel', done:s=>s.radalt.bitDone},
{n:46, g:'3 · Pilot Post-Start', t:'Standby ADI — <b>erect the gyro</b>',
 note:'At least two minutes before takeoff. Pull and turn the knob until the ball matches your attitude.',
 tgt:'stbyAdi', view:'panel', done:s=>s.sw.stbyAdi==='erect'},
{n:47, g:'3 · Pilot Post-Start', t:'Jester — datalink <b>mode and host</b> set',
 note:'A, A → LCTRL+7 DATA LINK RADIO → SET MODE → Tactical Datalink System, then SET HOST.',
 tgt:'comms:jester', done:s=>s.dl.mode&&s.dl.host},
{n:48, g:'3 · Pilot Post-Start', t:'Set <b>lights as required</b>, then taxi when ready. <b>Ready to taxi.</b>',
 note:'Guide steps 56–58 and 61 (kneeboard pages and the KY-28 encryption key) have no equivalent here — there is no kneeboard to open.',
 tgt:'extLights', view:'console', done:s=>s.touched.extLights&&s.ins.complete},

/* ---------------- 4. BEFORE TAKEOFF (guide Part 5, steps 8-9) ---------------- */
{n:49, g:'4 · Out of Oversweep', t:'Emergency Wing Sweep handle — <b>full forward to 20°</b>',
 note:'Scroll the wheel or left-click and drag the handle all the way forward.',
 tgt:'wingSweep', view:'console', done:s=>s.sw.wingSweep!=='oversweep'},
{n:50, g:'4 · Out of Oversweep', t:'Push the handle <b>down into the detent</b> and flip the cover over it',
 note:'Right-click to seat it. Until it is in the detent the wings stay in emergency mode.',
 tgt:'wingSweep', view:'console', done:s=>s.sw.wingSweep==='detent'},
{n:51, g:'4 · Out of Oversweep', t:'Press <b>MASTER RESET</b> — resets the CADC',
 note:'Very important. Without it the wing sweep AUTO mode will not work properly, and the thumb switch will not either.',
 tgt:'masterReset', view:'panel', done:s=>s.cadcReset&&s.sw.wingSweep==='detent'},
{n:52, g:'4 · Out of Oversweep', t:'Wings driving to <b>20°</b> — AUTO mode restored',
 tgt:'wingSweep', view:'console', done:s=>s.sweep<=20.5&&s.cadcReset},
];
