/* Blocks shared by both RIO alignment procedures.
   Sections 4 and 5 of Part 4 differ only in the middle: ashore you type the
   present position into the CAP, on the boat CAINS hands it across. */

export const RIO_PRE = [
{g:'1 · RIO Pre-Align', t:'ICS switch — <b>HOT MIC</b>',
 tgt:'rioIcs', view:'rioL', done:s=>s.sw.rioIcs==='hot'},
{g:'1 · RIO Pre-Align', t:'Verify <b>ground power</b> is connected',
 note:'The WCS cannot run without it.', tgt:'comms:ground', done:s=>s.power},
{g:'1 · RIO Pre-Align', t:'Wait for the pilot — <b>both engines running</b> and <b>AIR SOURCE BOTH ENG</b>',
 note:'The INS needs the WCS, the WCS needs ECS cooling air, and that needs both engines plus bleed air selected. Listen for his calls.',
 tgt:'scTid_rioC', view:'rioC', done:s=>s.eng.L.n2>55&&s.eng.R.n2>55&&s.sw.airSource==='both'},
{g:'1 · RIO Pre-Align', t:'Liquid Cooling switch — <b>FWD / ON</b>',
 note:'Starts the AWG-9 cooling. Third of the three conditions the WCS needs.',
 tgt:'liquidCool', view:'rioL', done:s=>s.sw.liquidCool==='fwd'},
{g:'1 · RIO Pre-Align', t:'WCS switch — <b>STANDBY</b> (middle)',
 tgt:'wcsMode', view:'rioR', done:s=>s.sw.wcsMode==='stby'||s.sw.wcsMode==='xmt'},
{g:'1 · RIO Pre-Align', t:'Wait ~<b>40 seconds</b> for the TID and DDD to power on',
 tgt:'scTid_rioC', view:'rioC', done:s=>s.rio.wcsUp},
]

export const RIO_POST = [
{g:'4 · RIO Post-Align', t:'RIO Oxygen switch — <b>ON</b>',
 tgt:'rioOxygen', view:'rioL', done:s=>s.sw.rioOxygen==='on'},
{g:'4 · RIO Post-Align', t:'RIO ejection seat — <b>ARMED</b>, canopy <b>CLOSED</b>',
 note:'LSHIFT+E and LCTRL+C in the sim.',
 tgt:'ejectSeat', done:s=>s.sw.ejectSeat==='armed'&&s.sw.canopy==='closed'},
{g:'4 · RIO Post-Align', t:'V/UHF radio function selector — <b>T/R +G</b>',
 tgt:'vuhfFunc', view:'rioL', done:s=>s.sw.vuhfFunc==='trg'},
{g:'4 · RIO Post-Align', t:'RIO TACAN function selector — <b>T/R</b>',
 tgt:'rioTacanFunc', view:'rioL', done:s=>s.sw.rioTacanFunc==='tr'},
{g:'4 · RIO Post-Align', t:'RIO standby ADI — <b>erect the gyro</b>',
 note:'At least two minutes before takeoff.',
 tgt:'rioStbyAdi', view:'rioC', done:s=>s.sw.rioStbyAdi==='erect'},
{g:'4 · RIO Post-Align', t:'IR / TV (TCS) power — <b>STANDBY</b>',
 note:'Two-minute warm-up. It goes to ON once you are airborne.',
 tgt:'irtvPower', view:'rioR', done:s=>s.sw.irtvPower!=='off'},
{g:'4 · RIO Post-Align', t:'AN/ALR-67 RWR power — <b>ON</b>',
 note:'The RWR only activates once the aircraft is in the air.',
 tgt:'alr67Power', view:'rioR', done:s=>s.sw.alr67Power==='on'},
{g:'4 · RIO Post-Align', t:'AN/ALQ-126 DECM jammer mode — <b>STANDBY</b>',
 tgt:'decmMode', view:'rioR', done:s=>s.sw.decmMode==='stby'},
{g:'4 · RIO Post-Align', t:'Datalink power — <b>ON</b>, mode — <b>TAC</b>',
 note:'Frequency is set on the kneeboard TACTICAL DATALINK SYSTEMS page — 309.20 for the E-2C. The wheels are not modelled here.',
 tgt:'dlPower', view:'rioR', done:s=>s.sw.dlPower==='on'&&s.sw.dlModeSw==='tac'},
{g:'4 · RIO Post-Align', t:'IFF Mode 4 power — <b>ON</b>',
 tgt:'iffMode4', view:'rioR', done:s=>s.sw.iffMode4==='on'},
{g:'4 · RIO Post-Align', t:'AN/ALE-39 PWR / MODE — <b>MAN</b> or <b>AUTO (CHAFF)</b>, as required',
 tgt:'ale39Mode', view:'rioR', done:s=>s.sw.ale39Mode!=='off'},
{g:'4 · RIO Post-Align', t:'Flare mode — <b>PILOT</b>',
 note:'Lets the front-seater punch flares with the DLC button.',
 tgt:'flareMode', view:'rioR', done:s=>s.sw.flareMode==='pilot'},
{g:'4 · RIO Post-Align', t:'After the 3-minute radar warm-up and once airborne — WCS <b>XMT</b>',
 tgt:'wcsMode', view:'rioR', done:s=>s.sw.wcsMode==='xmt'},
{g:'4 · RIO Post-Align', t:'IR / TV — <b>ON</b> once airborne. <b>Ready to taxi.</b>',
 tgt:'irtvPower', view:'rioR', done:s=>s.sw.irtvPower==='on'},
]
