/* ============================================================
   F/A-18C HORNET · CONTROLS
   Coordinates are pixels in the 1920x1080 space of each view image.

   view    'front'  forward instrument panel, UFC, IFEI, AMPCD, standby
           'knees'  left vertical panel, centre pedestal, right vertical panel
           'lconF'  left console, FORWARD  — ground power, exterior lights
           'lconM'  left console, MIDDLE   — engine, fuel, FCS
           'lconA'  left console, AFT      — comm, IFF, oxygen
           'rcon'   right console

   EVERY VIEW IS A SINGLE STRAIGHT CROP of the cockpit drawing. Nothing is
   moved, rotated or rearranged to fit the frame. Where a panel is too long to
   read in one view — the left console runs fore to aft — it is split into
   SEQUENTIAL views along its own axis, named for where it sits in the jet. If
   a switch is on the left console aft, it is on the aft tab, on the left.

   GENERATED, NOT TYPED. The hotspots were measured against the full cockpit
   layout drawing, and tools/compose.py cut that drawing into the four view
   images above while recording the transform for every piece it placed. Both
   the pixels and these rects went through that one transform, so the picture
   and the hitboxes cannot drift apart. Re-cut the views and regenerate; do not
   nudge numbers here by hand unless you are correcting a measurement.

   states  listed cold-jet-first, which is the position a parked Hornet is
           found in, so `init` is always states[0].
   ============================================================ */

export const controls = [

  /* ===== FRONT · Left Main Instrument Panel ============================ */
  { id:'masterCaution', view:'front', kind:'push', x:515, y:58, w:60, h:60,
    name:'MASTER CAUTION light / reset',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ready', view:'front', kind:'lamp', x:212, y:275, w:34, h:31,
    name:'READY / DISCH light' },
  { id:'fireExtgh', view:'front', kind:'push', x:212, y:327, w:35, h:35,
    name:'FIRE / EXTGH pushbutton (left engine)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'masterModeAA', view:'front', kind:'push', x:188, y:370, w:26, h:26,
    name:'A/A master mode', states:['off','aa'],
    lab:{off:'OFF', aa:'A/A'}, init:'off' },
  { id:'masterModeAG', view:'front', kind:'push', x:188, y:397, w:26, h:26,
    name:'A/G master mode', states:['off','ag'],
    lab:{off:'OFF', ag:'A/G'}, init:'off' },
  { id:'masterArm', view:'front', kind:'sw', x:185, y:428, w:54, h:65,
    name:'MASTER ARM switch', states:['safe','arm'],
    lab:{safe:'SAFE', arm:'ARM'}, init:'safe' },
  { id:'emergJettLbl', view:'front', kind:'push', x:167, y:515, w:76, h:92,
    name:'EMERG JETT button', states:['stowed','pressed'],
    lab:{stowed:'STOWED', pressed:'PRESSED'}, init:'stowed' },
  { id:'ddiLBright', view:'front', kind:'knob', x:426, y:132, w:56, h:56,
    name:'Left DDI brightness knob', states:['off','night','day'],
    lab:{off:'OFF', night:'NIGHT', day:'DAY'}, init:'off', angles:[-55,0,55] },
  { id:'ddiL', view:'front', kind:'lamp', x:279, y:222, w:190, h:190,
    name:'Left DDI (Digital Display Indicator)' },

  /* ===== FRONT · Up-Front Controller =================================== */
  { id:'ufcIP', view:'front', kind:'push', x:703, y:132, w:41, h:41,
    name:'UFC I/P button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcAdf', view:'front', kind:'sw', x:699, y:176, w:43, h:52,
    name:'ADF switch (ADF / OFF / ADF)', states:['adf2','off','adf1'],
    lab:{off:'OFF', adf1:'ADF 1', adf2:'ADF 2'}, init:'off' },
  { id:'comm1Vol', view:'front', kind:'knob', x:698, y:229, w:51, h:51,
    name:'COMM 1 volume / channel knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'comm2Vol', view:'front', kind:'knob', x:1074, y:229, w:51, h:51,
    name:'COMM 2 volume / channel knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'ufcKeypad', view:'front', kind:'push', x:766, y:191, w:126, h:126,
    name:'UFC keypad (0–9)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcClr', view:'front', kind:'push', x:763, y:296, w:41, h:41,
    name:'UFC CLR key',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcEnt', view:'front', kind:'push', x:856, y:296, w:41, h:41,
    name:'UFC ENT key',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcOsb', view:'front', kind:'push', x:895, y:198, w:68, h:68,
    name:'UFC option select buttons',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcBrt', view:'front', kind:'knob', x:1077, y:130, w:45, h:45,
    name:'UFC brightness knob (BRT / DIM)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'emcon', view:'front', kind:'push', x:1078, y:176, w:43, h:52,
    name:'EM CON switch', states:['norm','emcon'],
    lab:{norm:'NORM', emcon:'EMCON'}, init:'norm' },
  { id:'ufcAP', view:'front', kind:'push', x:766, y:365, w:37, h:37,
    name:'UFC A/P button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcIFF', view:'front', kind:'push', x:809, y:365, w:37, h:37,
    name:'UFC IFF button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcTCN', view:'front', kind:'push', x:852, y:365, w:37, h:37,
    name:'UFC TCN button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcILS', view:'front', kind:'push', x:894, y:365, w:37, h:37,
    name:'UFC ILS button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcDL', view:'front', kind:'push', x:937, y:365, w:37, h:37,
    name:'UFC D/L button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcBCN', view:'front', kind:'push', x:980, y:365, w:37, h:37,
    name:'UFC BCN button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcOnOff', view:'front', kind:'push', x:1022, y:365, w:37, h:37,
    name:'UFC ON/OFF button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'bitPanel', view:'front', kind:'push', x:1025, y:1, w:70, h:70,
    name:'GO / NOGO lights and BIT button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },

  /* ===== FRONT · HUD Control Panel ===================================== */
  { id:'hudSymRej', view:'front', kind:'knob', x:702, y:457, w:51, h:51,
    name:'HUD symbology reject knob (NORM / REJ 1 / REJ 2)', states:['norm','rej1','rej2'],
    lab:{norm:'NORM', rej1:'REJ 1', rej2:'REJ 2'}, init:'norm', angles:[-50,0,50] },
  { id:'hudBright', view:'front', kind:'knob', x:780, y:449, w:38, h:67,
    name:'HUD symbology brightness lever', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-60,60] },
  { id:'hudDayNight', view:'front', kind:'knob', x:846, y:457, w:51, h:51,
    name:'HUD DAY / NIGHT selector', states:['night','day'],
    lab:{night:'NIGHT', day:'DAY'}, init:'night', angles:[-50,50] },
  { id:'blkLvl', view:'front', kind:'knob', x:919, y:460, w:51, h:51,
    name:'BLK LVL knob (black level)', states:['min','set'],
    lab:{min:'MIN', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hudWB', view:'front', kind:'knob', x:988, y:460, w:51, h:51,
    name:'W/B VID knob (video contrast)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hudBal', view:'front', kind:'knob', x:1066, y:460, w:51, h:51,
    name:'BAL / SYM knob (video–symbology balance)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'aoaIndexer', view:'front', kind:'knob', x:797, y:526, w:47, h:47,
    name:'AoA indexer brightness (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'altSw', view:'front', kind:'sw', x:874, y:522, w:45, h:54,
    name:'ALT switch (BARO / RDR)', states:['rdr','baro'],
    lab:{baro:'BARO', rdr:'RDR'}, init:'baro' },
  { id:'attSw', view:'front', kind:'sw', x:947, y:522, w:45, h:54,
    name:'ATT switch (INS / AUTO / STBY)', states:['stby','auto','ins'],
    lab:{stby:'STBY', auto:'AUTO', ins:'INS'}, init:'stby' },

  /* ===== FRONT · Right Main Instrument Panel =========================== */
  { id:'ddiRBright', view:'front', kind:'knob', x:1331, y:132, w:56, h:56,
    name:'Right DDI brightness knob', states:['off','night','day'],
    lab:{off:'OFF', night:'NIGHT', day:'DAY'}, init:'off', angles:[-55,0,55] },
  { id:'ddiR', view:'front', kind:'lamp', x:1415, y:222, w:190, h:190,
    name:'Right DDI (Digital Display Indicator)' },
  { id:'fireExtghR', view:'front', kind:'push', x:1298, y:57, w:54, h:54,
    name:'FIRE / EXTGH pushbutton (right engine / APU)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'irCool', view:'front', kind:'sw', x:1569, y:308, w:49, h:59,
    name:'IR COOL switch (ORIDE / NORM / OFF)', states:['off','norm','oride'],
    lab:{off:'OFF', norm:'NORM', oride:'ORIDE'}, init:'off' },
  { id:'hmdKnob', view:'front', kind:'knob', x:1581, y:385, w:51, h:51,
    name:'HMD brightness knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'spinRcvy', view:'front', kind:'sw', x:1563, y:471, w:56, h:68,
    name:'SPIN RCVY switch (NORM / RCVY)', states:['norm','rcvy'],
    lab:{norm:'NORM', rcvy:'RCVY'}, init:'norm' },
  { id:'stbyCompass', view:'front', kind:'lamp', x:1672, y:514, w:97, h:88,
    name:'Standby magnetic compass' },

  /* ===== FRONT · IFEI & Video Record =================================== */
  { id:'ifei', view:'front', kind:'lamp', x:360, y:720, w:129, h:117,
    name:'IFEI (Integrated Fuel / Engine Indicator)' },
  { id:'ifeiMode', view:'front', kind:'push', x:491, y:672, w:33, h:33,
    name:'IFEI MODE button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiQty', view:'front', kind:'push', x:491, y:707, w:33, h:33,
    name:'IFEI QTY button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiUp', view:'front', kind:'push', x:491, y:742, w:33, h:33,
    name:'IFEI ▲ (up) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiDown', view:'front', kind:'push', x:491, y:776, w:33, h:33,
    name:'IFEI ▼ (down) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiZone', view:'front', kind:'push', x:491, y:811, w:33, h:33,
    name:'IFEI ZONE button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiET', view:'front', kind:'push', x:491, y:844, w:33, h:33,
    name:'IFEI ET (elapsed time) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'vrecHmd', view:'front', kind:'knob', x:378, y:927, w:47, h:47,
    name:'Video record source — HMD / LDDI / RDDI', states:['hmd','lddi','rddi'],
    lab:{hmd:'HMD', lddi:'LDDI', rddi:'RDDI'}, init:'hmd', angles:[-50,0,50] },
  { id:'vrecHud', view:'front', kind:'knob', x:455, y:927, w:47, h:47,
    name:'Video record source — HUD / LDIR / RDDI', states:['hud','ldir','rddi'],
    lab:{hud:'HUD', ldir:'LDIR', rddi:'RDDI'}, init:'hud', angles:[-50,0,50] },
  { id:'vrecMode', view:'front', kind:'knob', x:559, y:927, w:47, h:47,
    name:'Video record MAN / OFF / AUTO', states:['off','man','auto'],
    lab:{off:'OFF', man:'MAN', auto:'AUTO'}, init:'off', angles:[-50,0,50] },

  /* ===== FRONT · Jettison Station Select =============================== */
  { id:'jettCtr', view:'front', kind:'push', x:236, y:730, w:37, h:37,
    name:'JETT station select — CTR',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettLI', view:'front', kind:'push', x:219, y:771, w:33, h:33,
    name:'JETT station select — LI (left inboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettRI', view:'front', kind:'push', x:257, y:771, w:33, h:33,
    name:'JETT station select — RI (right inboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettLO', view:'front', kind:'push', x:219, y:811, w:33, h:33,
    name:'JETT station select — LO (left outboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettRO', view:'front', kind:'push', x:257, y:811, w:33, h:33,
    name:'JETT station select — RO (right outboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'flapsAdvisory', view:'front', kind:'lamp', x:234, y:928, w:41, h:37,
    name:'FLAPS advisory light' },

  /* ===== FRONT · AMPCD ================================================= */
  { id:'ampcd', view:'front', kind:'lamp', x:810, y:788, w:190, h:190,
    name:'AMPCD (Advanced Multi-Purpose Colour Display)' },
  { id:'ampcdBright', view:'front', kind:'knob', x:883, y:623, w:49, h:49,
    name:'AMPCD brightness knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-60,60] },
  { id:'ampcdDayNgt', view:'front', kind:'sw', x:731, y:620, w:54, h:65,
    name:'AMPCD DAY / NGT switch', states:['day','ngt'],
    lab:{day:'DAY', ngt:'NGT'}, init:'day' },
  { id:'ampcdSym', view:'front', kind:'knob', x:990, y:632, w:45, h:45,
    name:'AMPCD SYM (symbology) knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ampcdGain', view:'front', kind:'knob', x:725, y:1028, w:49, h:49,
    name:'AMPCD GAIN control',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ampcdCont', view:'front', kind:'knob', x:1039, y:1028, w:49, h:49,
    name:'AMPCD CONT (contrast) control',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hdgKnob', view:'front', kind:'knob', x:683, y:626, w:47, h:47,
    name:'HDG (heading) set knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'crsKnob', view:'front', kind:'knob', x:1082, y:626, w:47, h:47,
    name:'CRS (course) set knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },

  /* ===== FRONT · Standby Instruments =================================== */
  { id:'stbyAdi', view:'front', kind:'lamp', x:1197, y:678, w:145, h:131,
    name:'Standby attitude indicator' },
  { id:'stbyAdiCage', view:'front', kind:'knob', x:1333, y:799, w:47, h:47,
    name:'Standby ADI cage / TEST knob', states:['caged','uncaged'],
    lab:{caged:'CAGED', uncaged:'UNCAGED'}, init:'caged', angles:[-50,50] },
  { id:'rwrAzimuth', view:'front', kind:'lamp', x:1420, y:680, w:145, h:131,
    name:'RWR azimuth indicator (ALR-67)' },
  { id:'rwrInt', view:'front', kind:'knob', x:1550, y:795, w:45, h:45,
    name:'RWR INT (intensity) knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'stbyAsi', view:'front', kind:'lamp', x:1160, y:857, w:129, h:117,
    name:'Standby airspeed indicator' },
  { id:'stbyAlt', view:'front', kind:'lamp', x:1322, y:857, w:129, h:117,
    name:'Standby barometric altimeter' },
  { id:'stbyVvi', view:'front', kind:'lamp', x:1483, y:857, w:129, h:117,
    name:'Vertical velocity indicator' },

  /* ===== KNEES · Landing Gear Panel ==================================== */
  { id:'gearHandle', view:'knees', kind:'lever', x:105, y:138, w:52, h:89,
    name:'Landing gear handle', states:['down','up'],
    lab:{up:'UP', down:'DOWN'}, init:'up' },
  { id:'downLockOride', view:'knees', kind:'push', x:66, y:152, w:40, h:48,
    name:'DOWN LOCK ORIDE button', states:['norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'warnToneSil', view:'knees', kind:'push', x:53, y:90, w:33, h:33,
    name:'WARN / TONE SIL button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'emergGear', view:'knees', kind:'lever', x:97, y:75, w:57, h:69,
    name:'EMERG landing gear ROTATE AND PULL handle', states:['stowed','pulled'],
    lab:{stowed:'STOWED', pulled:'PULLED'}, init:'stowed' },

  /* ===== KNEES · Select Jettison & Brakes ============================== */
  { id:'launchBar', view:'knees', kind:'sw', x:55, y:254, w:42, h:51,
    name:'LAUNCH BAR switch (RETRACT / EXTEND)', states:['extend','retract'],
    lab:{retract:'RETRACT', extend:'EXTEND'}, init:'retract' },
  { id:'flapSw', view:'knees', kind:'sw', x:119, y:255, w:42, h:51,
    name:'FLAP switch (AUTO / HALF / FULL)', states:['full','half','auto'],
    lab:{auto:'AUTO', half:'HALF', full:'FULL'}, init:'auto' },
  { id:'selectJett', view:'knees', kind:'knob', x:187, y:262, w:80, h:80,
    name:'SELECT JETT knob and JETT button', states:['safe','racklchr','stores','lfusmsl','rfusmsl'],
    lab:{safe:'SAFE', racklchr:'RACK/LCHR', stores:'STORES', lfusmsl:'L FUS MSL', rfusmsl:'R FUS MSL'}, init:'safe', angles:[0,55,110,-55,-110] },
  { id:'ldgTaxiLight', view:'knees', kind:'sw', x:56, y:339, w:40, h:48,
    name:'LDG/TAXI LIGHT switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'antiSkid', view:'knees', kind:'sw', x:121, y:325, w:40, h:48,
    name:'ANTI SKID switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'emergBrk', view:'knees', kind:'lever', x:239, y:334, w:58, h:70,
    name:'EMERG BRK PULL handle', states:['stowed','pulled'],
    lab:{stowed:'STOWED', pulled:'PULLED'}, init:'stowed' },
  { id:'parkBrake', view:'knees', kind:'lever', x:184, y:345, w:46, h:80,
    name:'PARKING BRAKE lever', states:['released','engaged'],
    lab:{engaged:'ENGAGED', released:'RELEASED'}, init:'engaged' },
  { id:'hookBypass', view:'knees', kind:'sw', x:25, y:424, w:42, h:51,
    name:'HOOK BYPASS switch (FIELD / CARRIER)', states:['carrier','field'],
    lab:{field:'FIELD', carrier:'CARRIER'}, init:'field' },
  { id:'brakePress', view:'knees', kind:'lamp', x:98, y:395, w:72, h:65,
    name:'Hydraulic brake pressure gauge' },

  /* ===== KNEES · Hook & Wing Fold ====================================== */
  { id:'hookLever', view:'knees', kind:'lever', x:1681, y:167, w:55, h:94,
    name:'ARRESTING HOOK lever', states:['down','up'],
    lab:{up:'UP', down:'DOWN'}, init:'up' },
  { id:'hookLight', view:'knees', kind:'lamp', x:1685, y:44, w:50, h:45,
    name:'HOOK indicator light' },
  { id:'radarAlt', view:'knees', kind:'lamp', x:1566, y:235, w:104, h:94,
    name:'Radar altimeter and warning index' },
  { id:'buno', view:'knees', kind:'lamp', x:1680, y:263, w:56, h:51,
    name:'BUNO plate' },
  { id:'wingFold', view:'knees', kind:'lever', axis:'x', x:1758, y:216, w:86, h:149,
    name:'WING FOLD handle (FOLD / SPREAD, PULL–PUSH to lock)', states:['fold','spread','spreadlocked'],
    lab:{fold:'FOLD', spread:'SPREAD', spreadlocked:'SPREAD & LOCKED'}, init:'fold' },
  { id:'landingChecklist', view:'knees', kind:'lamp', x:1736, y:131, w:88, h:80,
    name:'LANDING checklist placard' },
  { id:'stbyCaution', view:'knees', kind:'lamp', x:1675, y:323, w:141, h:127,
    name:'Standby caution panel' },
  { id:'avCool', view:'knees', kind:'sw', x:1851, y:375, w:44, h:53,
    name:'AV COOL switch (NORM / EMERG)', states:['norm','emerg'],
    lab:{norm:'NORM', emerg:'EMERG'}, init:'norm' },
  { id:'hydPress', view:'knees', kind:'lamp', x:1559, y:363, w:80, h:73,
    name:'Hydraulic pressure gauge (HYD 1 / HYD 2)' },

  /* ===== KNEES · Countermeasures ======================================= */
  { id:'ecmJett', view:'knees', kind:'push', x:788, y:131, w:58, h:70,
    name:'ECM JETT button', states:['stowed','pressed'],
    lab:{stowed:'STOWED', pressed:'PRESSED'}, init:'stowed' },
  { id:'alr67Power', view:'knees', kind:'push', x:1011, y:128, w:35, h:35,
    name:'ALR-67 POWER button', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'cmdsDisType', view:'knees', kind:'knob', x:886, y:163, w:34, h:34,
    name:'DIS TYPE knob (A / U / F / N / I)', states:['off','a','u','f','n','i'],
    lab:{off:'OFF', a:'A', u:'U', f:'F', n:'N', i:'I'}, init:'off', angles:[-120,-72,-24,24,72,120] },
  { id:'dispenser', view:'knees', kind:'sw', x:800, y:243, w:40, h:48,
    name:'DISPENSER switch (ON / BYPASS / OFF)', states:['off','on','bypass'],
    lab:{off:'OFF', on:'ON', bypass:'BYPASS'}, init:'off' },
  { id:'ecmKnob', view:'knees', kind:'knob', x:897, y:216, w:57, h:57,
    name:'ECM selector (OFF / STBY / BIT / REC / XMIT)', states:['off','stby','bit','rec','xmit'],
    lab:{off:'OFF', stby:'STBY', bit:'BIT', rec:'REC', xmit:'XMIT'}, init:'off', angles:[-125,-70,-15,40,95] },
  { id:'auxRel', view:'knees', kind:'sw', x:830, y:341, w:40, h:48,
    name:'AUX REL switch (NORM / ENABLE)', states:['norm','enable'],
    lab:{norm:'NORM', enable:'ENABLE'}, init:'norm' },
  { id:'cabinPressAlt', view:'knees', kind:'lamp', x:969, y:339, w:96, h:87,
    name:'Cabin pressure altimeter' },

  /* ===== LCONF · Left Console — Power & Exterior Lights ================ */
  { id:'fireTest', view:'lconF', kind:'sw', x:1158, y:48, w:103, h:124,
    name:'FIRE & BLEED AIR TEST switch (TEST A / NORM / TEST B)', states:['testb','norm','testa'],
    lab:{norm:'NORM', testa:'TEST A', testb:'TEST B'}, init:'norm' },
  { id:'gndPwr1', view:'lconF', kind:'sw', x:905, y:179, w:77, h:93,
    name:'GND PWR 1 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr2', view:'lconF', kind:'sw', x:781, y:273, w:77, h:93,
    name:'GND PWR 2 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr3', view:'lconF', kind:'sw', x:905, y:346, w:77, h:93,
    name:'GND PWR 3 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr4', view:'lconF', kind:'sw', x:781, y:454, w:77, h:93,
    name:'GND PWR 4 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'extPwr', view:'lconF', kind:'sw', x:891, y:502, w:82, h:99,
    name:'EXT PWR switch (RESET / NORM / OFF)', states:['off','norm','reset'],
    lab:{norm:'NORM', reset:'RESET', off:'OFF'}, init:'norm' },
  { id:'genTie', view:'lconF', kind:'sw', x:540, y:862, w:137, h:166,
    name:'GEN TIE switch (NORM / RESET)', states:['norm','reset'],
    lab:{norm:'NORM', reset:'RESET'}, init:'norm' },
  { id:'formationLt', view:'lconF', kind:'knob', x:868, y:701, w:104, h:104,
    name:'FORMATION lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'positionLt', view:'lconF', kind:'knob', x:761, y:864, w:104, h:104,
    name:'POSITION lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  /* The throttle covers this corner of the exterior lights panel on this
     drawing, so the STROBE knob is not visible on any view. */
  { id:'strobeLt', tray:true, kind:'knob',
    name:'STROBE lights switch (BRT / OFF / DIM)', states:['dim','off','brt'],
    lab:{dim:'DIM', off:'OFF', brt:'BRT'}, init:'off', angles:[-60,0,60] },

  /* ===== LCONM · Left Console — Engine, Fuel & FCS ===================== */
  { id:'apuSw', view:'lconM', kind:'sw', x:438, y:275, w:132, h:160,
    name:'APU switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'apuReady', view:'lconM', kind:'lamp', x:577, y:291, w:111, h:100,
    name:'APU READY light' },
  { id:'engCrank', view:'lconM', kind:'sw', axis:'x', x:499, y:626, w:132, h:160,
    name:'ENG CRANK switch (L / OFF / R)', states:['l','off','r'],
    lab:{off:'OFF', l:'L', r:'R'}, init:'off' },
  { id:'probeSw', view:'lconM', kind:'sw', x:820, y:147, w:137, h:166,
    name:'Refuelling PROBE switch (EXTEND / RETRACT / EMERG EXTD)', states:['emergextd','retract','extend'],
    lab:{retract:'RETRACT', extend:'EXTEND', emergextd:'EMERG EXTD'}, init:'retract' },
  { id:'extTankWing', view:'lconM', kind:'sw', x:1012, y:78, w:109, h:132,
    name:'EXT TANKS WING switch (ORIDE / NORM / STOP)', states:['stop','norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE', stop:'STOP'}, init:'norm' },
  { id:'extTankCtr', view:'lconM', kind:'sw', x:1202, y:78, w:109, h:132,
    name:'EXT TANKS CTR switch (ORIDE / NORM / STOP)', states:['stop','norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE', stop:'STOP'}, init:'norm' },
  { id:'fuelDump', view:'lconM', kind:'sw', x:1356, y:180, w:125, h:152,
    name:'FUEL DUMP switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'toTrim', view:'lconM', kind:'push', x:1051, y:418, w:125, h:125,
    name:'T/O TRIM button (and RUD TRIM knob)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'fcsGain', view:'lconM', kind:'sw', x:1391, y:391, w:190, h:190,
    name:'FCS GAIN switch (NORM / ORIDE)', states:['norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'fcsReset', view:'lconM', kind:'push', x:1358, y:536, w:125, h:125,
    name:'FCS RESET button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'volIcs', view:'lconM', kind:'knob', x:827, y:906, w:115, h:115,
    name:'ICS volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volWpn', view:'lconM', kind:'knob', x:1000, y:906, w:115, h:115,
    name:'WPN volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volMidsA', view:'lconM', kind:'knob', x:1174, y:906, w:115, h:115,
    name:'MIDS A volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volAux', view:'lconM', kind:'knob', x:1353, y:906, w:115, h:115,
    name:'AUX volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },

  /* ===== LCONA · Left Console — Comm, IFF & Oxygen ===================== */
  { id:'antSelIff', view:'lconA', kind:'sw', axis:'x', x:622, y:121, w:86, h:104,
    name:'ANT SEL — IFF (UPPER / BOTH / LOWER)', states:['upper','both','lower'],
    lab:{both:'BOTH', upper:'UPPER', lower:'LOWER'}, init:'both' },
  { id:'antSelComm1', view:'lconA', kind:'sw', axis:'x', x:622, y:246, w:86, h:104,
    name:'ANT SEL — COMM 1 (UPPER / AUTO / LOWER)', states:['upper','auto','lower'],
    lab:{auto:'AUTO', upper:'UPPER', lower:'LOWER'}, init:'auto' },
  { id:'voxSw', view:'lconA', kind:'sw', axis:'x', x:818, y:42, w:81, h:99,
    name:'VOX / HOT MIC / COLD MIC switch', states:['vox','hotmic','coldmic'],
    lab:{coldmic:'COLD MIC', vox:'VOX', hotmic:'HOT MIC'}, init:'coldmic' },
  { id:'volRwr', view:'lconA', kind:'knob', x:946, y:52, w:79, h:79,
    name:'RWR volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volMidsB', view:'lconA', kind:'knob', x:1066, y:52, w:79, h:79,
    name:'MIDS B volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volTcn', view:'lconA', kind:'knob', x:1189, y:52, w:79, h:79,
    name:'TCN volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'ufcSw', view:'lconA', kind:'sw', axis:'x', x:1014, y:186, w:81, h:99,
    name:'UFC switch (ON / OFF)', states:['off','on'],
    lab:{on:'ON', off:'OFF'}, init:'on' },
  { id:'masterEmer', view:'lconA', kind:'sw', axis:'x', x:1188, y:186, w:81, h:99,
    name:'MASTER radio switch (NORM / EMER)', states:['emer','norm'],
    lab:{norm:'NORM', emer:'EMER'}, init:'norm' },
  { id:'gXmt', view:'lconA', kind:'sw', axis:'x', x:841, y:296, w:81, h:99,
    name:'G XMT switch (COMM 1 / OFF / COMM 2)', states:['comm1','off','comm2'],
    lab:{off:'OFF', comm1:'COMM 1', comm2:'COMM 2'}, init:'off' },
  { id:'rlySw', view:'lconA', kind:'sw', axis:'x', x:841, y:418, w:81, h:99,
    name:'RLY switch (CIPHER / OFF / PLAIN)', states:['cipher','off','plain'],
    lab:{off:'OFF', cipher:'CIPHER', plain:'PLAIN'}, init:'off' },
  { id:'ilsChannel', view:'lconA', kind:'knob', x:997, y:383, w:124, h:124,
    name:'ILS CHANNEL knob (1–20)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'iffMode4', view:'lconA', kind:'sw', axis:'x', x:1188, y:300, w:81, h:99,
    name:'IFF MODE 4 switch (DIS / AUD / OFF)', states:['dis','aud','off'],
    lab:{off:'OFF', dis:'DIS', aud:'AUD'}, init:'off' },
  { id:'crypto', view:'lconA', kind:'sw', axis:'x', x:1188, y:422, w:81, h:99,
    name:'IFF CRYPTO switch (HOLD / NORM / ZERO)', states:['hold','norm','zero'],
    lab:{norm:'NORM', hold:'HOLD', zero:'ZERO'}, init:'norm' },
  { id:'obogs', view:'lconA', kind:'sw', axis:'x', x:778, y:571, w:86, h:104,
    name:'OBOGS switch (ON / OFF)', states:['on','off'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'oxyFlow', view:'lconA', kind:'knob', x:988, y:579, w:115, h:115,
    name:'OXY FLOW knob (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-50,50] },
  { id:'hydIsol', view:'lconA', kind:'sw', axis:'x', x:487, y:715, w:86, h:104,
    name:'HYD ISOL switch (NORM / ORIDE)', states:['oride','norm'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'mcSw', view:'lconA', kind:'sw', axis:'x', x:491, y:933, w:86, h:104,
    name:'MC switch (MC 1 OFF / MC 2 OFF)', states:['mc1off','norm','mc2off'],
    lab:{norm:'NORM', mc1off:'MC 1 OFF', mc2off:'MC 2 OFF'}, init:'norm' },

  /* ===== RCON · Right Console — Electrical ============================= */
  { id:'battVolt', view:'rcon', kind:'lamp', x:877, y:37, w:99, h:89,
    name:'Battery voltage gauge' },
  { id:'lGen', view:'rcon', kind:'sw', x:886, y:145, w:55, h:66,
    name:'L GEN switch (NORM / OFF)', states:['off','norm'],
    lab:{norm:'NORM', off:'OFF'}, init:'norm' },
  { id:'battSw', view:'rcon', kind:'sw', x:990, y:145, w:55, h:66,
    name:'BATT switch (ON / OFF / ORIDE)', states:['oride','off','on'],
    lab:{off:'OFF', on:'ON', oride:'ORIDE'}, init:'off' },
  { id:'rGen', view:'rcon', kind:'sw', x:1092, y:145, w:55, h:66,
    name:'R GEN switch (NORM / OFF)', states:['off','norm'],
    lab:{norm:'NORM', off:'OFF'}, init:'norm' },

  /* ===== RCON · Right Console — ECS & Anti-Ice ========================= */
  { id:'ecsMode', view:'rcon', kind:'sw', x:893, y:264, w:55, h:66,
    name:'ECS MODE switch (AUTO / MAN / OFF-RAM)', states:['offram','man','auto'],
    lab:{auto:'AUTO', man:'MAN', offram:'OFF/RAM'}, init:'auto' },
  { id:'ecsTemp', view:'rcon', kind:'knob', x:983, y:262, w:69, h:69,
    name:'ECS TEMP knob (COLD / HOT)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-110,110] },
  { id:'cabinPressSw', view:'rcon', kind:'sw', x:1103, y:264, w:55, h:66,
    name:'CABIN PRESS switch (NORM / DUMP / RAM-DUMP)', states:['ramdump','dump','norm'],
    lab:{norm:'NORM', dump:'DUMP', ramdump:'RAM/DUMP'}, init:'norm' },
  { id:'pitotHeat', view:'rcon', kind:'sw', x:890, y:378, w:52, h:63,
    name:'PITOT ANTI ICE switch (ON / AUTO)', states:['auto','on'],
    lab:{auto:'AUTO', on:'ON'}, init:'auto' },
  { id:'engAntiIce', view:'rcon', kind:'sw', x:975, y:378, w:47, h:57,
    name:'ENG ANTI ICE switch (ON / OFF / TEST)', states:['test','off','on'],
    lab:{off:'OFF', on:'ON', test:'TEST'}, init:'off' },
  { id:'bleedAir', view:'rcon', kind:'knob', x:1068, y:375, w:69, h:69,
    name:'BLEED AIR knob (NORM / OFF / L OFF / R OFF / AUG PULL)', states:['norm','loff','roff','off'],
    lab:{norm:'NORM', loff:'L OFF', roff:'R OFF', off:'OFF'}, init:'norm', angles:[0,-95,95,175] },

  /* ===== RCON · Right Console — Interior Lights ======================== */
  { id:'consolesLt', view:'rcon', kind:'knob', x:909, y:492, w:57, h:57,
    name:'CONSOLES lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'instPnlLt', view:'rcon', kind:'knob', x:998, y:492, w:57, h:57,
    name:'INST PNL lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'floodLt', view:'rcon', kind:'knob', x:1085, y:492, w:57, h:57,
    name:'FLOOD lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'ltTest', view:'rcon', kind:'sw', x:885, y:581, w:47, h:57,
    name:'LT TEST switch (TEST / OFF)', states:['off','test'],
    lab:{off:'OFF', test:'TEST'}, init:'off' },
  { id:'warnCautLt', view:'rcon', kind:'knob', x:953, y:583, w:54, h:54,
    name:'WARN / CAUT brightness knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'chartLt', view:'rcon', kind:'knob', x:1042, y:583, w:54, h:54,
    name:'CHART light knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ltMode', view:'rcon', kind:'sw', x:1110, y:581, w:47, h:57,
    name:'Lighting MODE switch (NITE / DAY)', states:['day','nvg'],
    lab:{day:'DAY', nvg:'NVG'}, init:'day' },

  /* ===== RCON · Right Console — Defog & Windshield ===================== */
  { id:'defog', view:'rcon', kind:'lever', x:1209, y:462, w:63, h:109,
    name:'DEFOG lever', states:['low','norm','high'],
    lab:{low:'LOW', norm:'NORM', high:'HIGH'}, init:'norm' },
  { id:'windshieldAntiIce', view:'rcon', kind:'sw', x:1231, y:654, w:58, h:71,
    name:'WINDSHIELD ANTI ICE switch', states:['rain','off','antiice'],
    lab:{rain:'RAIN', off:'OFF', antiice:'ANTI ICE'}, init:'off' },

  /* ===== RCON · Right Console — Sensors ================================ */
  { id:'flirSw', view:'rcon', kind:'sw', x:899, y:681, w:52, h:63,
    name:'FLIR switch (ON / STBY / OFF)', states:['off','stby','on'],
    lab:{off:'OFF', stby:'STBY', on:'ON'}, init:'off' },
  { id:'ltdr', view:'rcon', kind:'sw', x:992, y:690, w:52, h:63,
    name:'LTD/R switch (ARM / SAFE)', states:['aft','safe','arm'],
    lab:{aft:'AFT', safe:'SAFE', arm:'ARM'}, init:'safe' },
  { id:'lstNflr', view:'rcon', kind:'sw', x:1083, y:684, w:52, h:63,
    name:'LST/NFLR switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'radarKnob', view:'rcon', kind:'knob', x:895, y:762, w:84, h:84,
    name:'RADAR knob (OFF / STBY / OPR / PULL EMERG)', states:['off','stby','opr','emerg'],
    lab:{off:'OFF', stby:'STBY', opr:'OPR', emerg:'EMERG'}, init:'off', angles:[-120,-60,0,90] },
  { id:'insKnob', view:'rcon', kind:'knob', x:1069, y:762, w:84, h:84,
    name:'INS knob (OFF / CV / GND / NAV / IFA / GYRO / TEST)', states:['off','cv','gnd','nav','ifa','gyro','test'],
    lab:{off:'OFF', cv:'CV', gnd:'GND', nav:'NAV', ifa:'IFA', gyro:'GYRO', test:'TEST'}, init:'off', angles:[-135,-90,-45,20,65,115,155] },

  /* ===== RCON · Right Console — KY-58 Secure Voice ===================== */
  { id:'kyMode', view:'rcon', kind:'knob', x:907, y:902, w:61, h:61,
    name:'KY-58 MODE knob (P / C / LD / RV)', states:['p','c','ld','rv'],
    lab:{p:'P', c:'C', ld:'LD', rv:'RV'}, init:'p', angles:[-90,-30,30,90] },
  { id:'kyFill', view:'rcon', kind:'knob', x:986, y:954, w:54, h:54,
    name:'KY-58 FILL selector (1–6 / Z 1-5 / ALL)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'kyVolume', view:'rcon', kind:'knob', x:908, y:995, w:59, h:59,
    name:'KY-58 VOLUME knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'kyTd', view:'rcon', kind:'knob', x:1070, y:995, w:59, h:59,
    name:'KY-58 TD switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-50,50] },

  /* ===== NOT IN ANY VIEW ================================================
     Hand controls and the canopy: real, needed by the start-up model, and not
     drawn on a panel layout. That is what `tray` is for. */
  { id:'throttleL', tray:true, kind:'lever', name:'LEFT THROTTLE',
    states:['off','idle','mil','max'],
    lab:{off:'OFF', idle:'IDLE', mil:'MIL', max:'MAX'}, init:'off' },
  { id:'throttleR', tray:true, kind:'lever', name:'RIGHT THROTTLE',
    states:['off','idle','mil','max'],
    lab:{off:'OFF', idle:'IDLE', mil:'MIL', max:'MAX'}, init:'off' },
  { id:'canopy', tray:true, kind:'lever', name:'CANOPY HANDLE',
    states:['open','closed'], lab:{open:'OPEN', closed:'CLOSED'}, init:'open' },
  { id:'ejectSeat', tray:true, kind:'lever', name:'EJECTION SEAT HANDLE',
    states:['safe','armed'], lab:{safe:'SAFE', armed:'ARMED'}, init:'safe' },
  { id:'harness', tray:true, kind:'lever', name:'HARNESS LOCK LEVER',
    states:['unlocked','locked'], lab:{unlocked:'UNLOCKED', locked:'LOCKED'}, init:'unlocked' },
  { id:'fingerLifts', tray:true, kind:'lever', name:'THROTTLE FINGER LIFTS',
    states:['down','up'], lab:{down:'DOWN', up:'UP'}, init:'down' },
  { id:'hudGlass', tray:true, kind:'lamp', name:'HUD combiner glass' },
];
