/* ============================================================
   F/A-18C HORNET · CONTROLS
   Coordinates are pixels in the 1920x1080 space of each view image.

   view    'front'  forward instrument panel, UFC, IFEI, AMPCD, standby,
                    plus the knee panels, pedestal front and hook/wing-fold
                    panel, which the front photograph also covers
           'lcon'   left console: comm/IFF, oxygen, FCS, engine crank,
                    external tanks, exterior lights, ground power
           'rcon'   right console: electrics, ECS, interior lights,
                    sensors, INS, KY-58

    MEASURED, NOT INHERITED. The hotspots were measured against the three
    view photographs (DCS screenshots, 3840x2160, halved to the 1920x1080
    view space) panel by panel, then checked by rendering every rect back
    over the photos. Re-measure rather than nudge by hand; the overlay
    pass is what keeps the picture and the hitboxes honest.

    A handful of controls are not visible in any photo — the fire
    extinguisher panel, the standby compass — and live in the tray
    (`tray:true`), same as the hand controls always have. Two more — the
    fire & bleed air test switch and GND PWR 1 — are hidden by the throttle
    grip in the idle photo; they are `peek` controls, measured on the
    throttle-aft photo (`lconAlt.jpg`), which the left console view swings
    in whenever a step works one of them.

   states  listed cold-jet-first, which is the position a parked Hornet is
           found in, so `init` is always states[0].
   ============================================================ */

export const controls = [

  /* ===== FRONT · Left Main Instrument Panel ============================ */
  { id:'masterCaution', tray:true, kind:'push', 
    name:'MASTER CAUTION light / reset',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ready', tray:true, kind:'lamp', 
    name:'READY / DISCH light' },
  { id:'fireExtgh', tray:true, kind:'push', 
    name:'FIRE / EXTGH pushbutton (left engine)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'masterModeAA', view:'front', kind:'push', x:422, y:342, w:26, h:26,
    name:'A/A master mode', states:['off','aa'],
    lab:{off:'OFF', aa:'A/A'}, init:'off' },
  { id:'masterModeAG', view:'front', kind:'push', x:422, y:370, w:26, h:26,
    name:'A/G master mode', states:['off','ag'],
    lab:{off:'OFF', ag:'A/G'}, init:'off' },
  { id:'masterArm', view:'front', kind:'sw', x:410, y:405, w:62, h:48,
    name:'MASTER ARM switch', states:['safe','arm'],
    lab:{safe:'SAFE', arm:'ARM'}, init:'safe' },
  { id:'emergJettLbl', view:'front', kind:'push', x:392, y:467, w:122, h:76,
    name:'EMERG JETT button', states:['stowed','pressed'],
    lab:{stowed:'STOWED', pressed:'PRESSED'}, init:'stowed' },
  { id:'ddiLBright', view:'front', kind:'knob', x:599, y:166, w:51, h:51,
    name:'Left DDI brightness knob', states:['off','night','day'],
    lab:{off:'OFF', night:'NIGHT', day:'DAY'}, init:'off', angles:[-55,0,55] },
  { id:'ddiL', view:'front', kind:'lamp', x:527, y:237, w:198, h:212,
    name:'Left DDI (Digital Display Indicator)' },

  /* ===== FRONT · Up-Front Controller =================================== */
  { id:'ufcIP', view:'front', kind:'push', x:783, y:139, w:21, h:22,
    name:'UFC I/P button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcAdf', view:'front', kind:'sw', x:782, y:182, w:26, h:28,
    name:'ADF switch (ADF / OFF / ADF)', states:['adf2','off','adf1'],
    lab:{off:'OFF', adf1:'ADF 1', adf2:'ADF 2'}, init:'off' },
  { id:'comm1Vol', view:'front', kind:'knob', x:781, y:233, w:25, h:25,
    name:'COMM 1 volume / channel knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'comm2Vol', view:'front', kind:'knob', x:1073, y:234, w:25, h:24,
    name:'COMM 2 volume / channel knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'ufcKeypad', view:'front', kind:'push', x:825, y:172, w:108, h:140,
    name:'UFC keypad (0–9)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcClr', view:'front', kind:'push', x:826, y:284, w:29, h:28,
    name:'UFC CLR key',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcEnt', view:'front', kind:'push', x:902, y:284, w:32, h:28,
    name:'UFC ENT key',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcOsb', view:'front', kind:'push', x:939, y:170, w:26, h:144,
    name:'UFC option select buttons',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcBrt', view:'front', kind:'knob', x:1075, y:145, w:25, h:25,
    name:'UFC brightness knob (BRT / DIM)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'emcon', view:'front', kind:'push', x:1074, y:182, w:24, h:28,
    name:'EM CON switch', states:['norm','emcon'],
    lab:{norm:'NORM', emcon:'EMCON'}, init:'norm' },
  { id:'ufcAP', view:'front', kind:'push', x:834, y:342, w:24, h:24,
    name:'UFC A/P button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcIFF', view:'front', kind:'push', x:868, y:342, w:22, h:24,
    name:'UFC IFF button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcTCN', view:'front', kind:'push', x:898, y:342, w:24, h:24,
    name:'UFC TCN button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcILS', view:'front', kind:'push', x:932, y:342, w:22, h:24,
    name:'UFC ILS button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcDL', view:'front', kind:'push', x:964, y:342, w:22, h:24,
    name:'UFC D/L button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcBCN', view:'front', kind:'push', x:996, y:342, w:22, h:24,
    name:'UFC BCN button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ufcOnOff', view:'front', kind:'push', x:1028, y:342, w:24, h:24,
    name:'UFC ON/OFF button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'bitPanel', view:'front', kind:'push', x:942, y:130, w:24, h:24,
    name:'GO / NOGO lights and BIT button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },

  /* ===== FRONT · HUD Control Panel ===================================== */
  { id:'hudSymRej', view:'front', kind:'knob', x:800, y:422, w:32, h:31,
    name:'HUD symbology reject knob (NORM / REJ 1 / REJ 2)', states:['norm','rej1','rej2'],
    lab:{norm:'NORM', rej1:'REJ 1', rej2:'REJ 2'}, init:'norm', angles:[-50,0,50] },
  { id:'hudBright', view:'front', kind:'knob', x:846, y:422, w:38, h:38,
    name:'HUD symbology brightness lever', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-60,60] },
  { id:'hudDayNight', view:'front', kind:'knob', x:902, y:422, w:28, h:30,
    name:'HUD DAY / NIGHT selector', states:['night','day'],
    lab:{night:'NIGHT', day:'DAY'}, init:'night', angles:[-50,50] },
  { id:'blkLvl', view:'front', kind:'knob', x:948, y:424, w:33, h:34,
    name:'BLK LVL knob (black level)', states:['min','set'],
    lab:{min:'MIN', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hudWB', view:'front', kind:'knob', x:1002, y:424, w:22, h:34,
    name:'W/B VID knob (video contrast)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hudBal', view:'front', kind:'knob', x:1049, y:422, w:34, h:40,
    name:'BAL / SYM knob (video–symbology balance)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'aoaIndexer', view:'front', kind:'knob', x:871, y:470, w:28, h:31,
    name:'AoA indexer brightness (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'altSw', view:'front', kind:'sw', x:920, y:469, w:24, h:28,
    name:'ALT switch (BARO / RDR)', states:['rdr','baro'],
    lab:{baro:'BARO', rdr:'RDR'}, init:'baro' },
  { id:'attSw', view:'front', kind:'sw', x:969, y:470, w:24, h:29,
    name:'ATT switch (INS / AUTO / STBY)', states:['stby','auto','ins'],
    lab:{stby:'STBY', auto:'AUTO', ins:'INS'}, init:'stby' },

  /* ===== FRONT · Right Main Instrument Panel =========================== */
  { id:'ddiRBright', view:'front', kind:'knob', x:1235, y:167, w:50, h:49,
    name:'Right DDI brightness knob', states:['off','night','day'],
    lab:{off:'OFF', night:'NIGHT', day:'DAY'}, init:'off', angles:[-55,0,55] },
  { id:'ddiR', view:'front', kind:'lamp', x:1146, y:235, w:220, h:217,
    name:'Right DDI (Digital Display Indicator)' },
  { id:'fireExtghR', tray:true, kind:'push', 
    name:'FIRE / EXTGH pushbutton (right engine / APU)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'irCool', view:'front', kind:'sw', x:1416, y:312, w:35, h:35,
    name:'IR COOL switch (ORIDE / NORM / OFF)', states:['off','norm','oride'],
    lab:{off:'OFF', norm:'NORM', oride:'ORIDE'}, init:'off' },
  { id:'hmdKnob', view:'front', kind:'knob', x:1436, y:365, w:35, h:36,
    name:'HMD brightness knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'spinRcvy', view:'front', kind:'sw', x:1452, y:444, w:48, h:68,
    name:'SPIN RCVY switch (NORM / RCVY)', states:['norm','rcvy'],
    lab:{norm:'NORM', rcvy:'RCVY'}, init:'norm' },
  { id:'stbyCompass', tray:true, kind:'lamp', 
    name:'Standby magnetic compass' },

  /* ===== FRONT · IFEI & Video Record =================================== */
  { id:'ifei', view:'front', kind:'lamp', x:598, y:554, w:192, h:121,
    name:'IFEI (Integrated Fuel / Engine Indicator)' },
  { id:'ifeiMode', view:'front', kind:'push', x:695, y:556, w:18, h:14,
    name:'IFEI MODE button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiQty', view:'front', kind:'push', x:695, y:574, w:18, h:14,
    name:'IFEI QTY button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiUp', view:'front', kind:'push', x:697, y:595, w:14, h:12,
    name:'IFEI ▲ (up) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiDown', view:'front', kind:'push', x:697, y:614, w:14, h:12,
    name:'IFEI ▼ (down) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiZone', view:'front', kind:'push', x:693, y:643, w:22, h:12,
    name:'IFEI ZONE button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'ifeiET', view:'front', kind:'push', x:693, y:664, w:22, h:13,
    name:'IFEI ET (elapsed time) button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'vrecHmd', view:'front', kind:'knob', x:640, y:698, w:26, h:26,
    name:'Video record source — HMD / LDDI / RDDI', states:['hmd','lddi','rddi'],
    lab:{hmd:'HMD', lddi:'LDDI', rddi:'RDDI'}, init:'hmd', angles:[-50,0,50] },
  { id:'vrecHud', view:'front', kind:'knob', x:685, y:696, w:29, h:29,
    name:'Video record source — HUD / LDIR / RDDI', states:['hud','ldir','rddi'],
    lab:{hud:'HUD', ldir:'LDIR', rddi:'RDDI'}, init:'hud', angles:[-50,0,50] },
  { id:'vrecMode', view:'front', kind:'knob', x:740, y:696, w:29, h:29,
    name:'Video record MAN / OFF / AUTO', states:['off','man','auto'],
    lab:{off:'OFF', man:'MAN', auto:'AUTO'}, init:'off', angles:[-50,0,50] },

  /* ===== FRONT · Jettison Station Select =============================== */
  { id:'jettCtr', view:'front', kind:'push', x:532, y:589, w:22, h:18,
    name:'JETT station select — CTR',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettLI', view:'front', kind:'push', x:524, y:610, w:21, h:19,
    name:'JETT station select — LI (left inboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettRI', view:'front', kind:'push', x:545, y:610, w:22, h:19,
    name:'JETT station select — RI (right inboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettLO', view:'front', kind:'push', x:524, y:634, w:21, h:19,
    name:'JETT station select — LO (left outboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'jettRO', view:'front', kind:'push', x:545, y:634, w:22, h:19,
    name:'JETT station select — RO (right outboard)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'flapsAdvisory', view:'front', kind:'lamp', x:526, y:665, w:40, h:36,
    name:'FLAPS advisory light' },

  /* ===== FRONT · AMPCD ================================================= */
  { id:'ampcd', view:'front', kind:'lamp', x:839, y:588, w:209, h:209,
    name:'AMPCD (Advanced Multi-Purpose Colour Display)' },
  { id:'ampcdBright', view:'front', kind:'knob', x:923, y:532, w:28, h:28,
    name:'AMPCD brightness knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-60,60] },
  { id:'ampcdDayNgt', view:'front', kind:'sw', x:837, y:547, w:23, h:28,
    name:'AMPCD DAY / NGT switch', states:['day','ngt'],
    lab:{day:'DAY', ngt:'NGT'}, init:'day' },
  { id:'ampcdSym', view:'front', kind:'knob', x:996, y:556, w:26, h:26,
    name:'AMPCD SYM (symbology) knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ampcdGain', view:'front', kind:'knob', x:804, y:780, w:19, h:50,
    name:'AMPCD GAIN control',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ampcdCont', view:'front', kind:'knob', x:1062, y:780, w:19, h:50,
    name:'AMPCD CONT (contrast) control',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'hdgKnob', view:'front', kind:'knob', x:796, y:531, w:31, h:31,
    name:'HDG (heading) set knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'crsKnob', view:'front', kind:'knob', x:1056, y:529, w:32, h:32,
    name:'CRS (course) set knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },

  /* ===== FRONT · Standby Instruments =================================== */
  { id:'stbyAdi', view:'front', kind:'lamp', x:1113, y:536, w:105, h:96,
    name:'Standby attitude indicator' },
  { id:'stbyAdiCage', view:'front', kind:'knob', x:1192, y:611, w:33, h:33,
    name:'Standby ADI cage / TEST knob', states:['caged','uncaged'],
    lab:{caged:'CAGED', uncaged:'UNCAGED'}, init:'caged', angles:[-50,50] },
  { id:'rwrAzimuth', view:'front', kind:'lamp', x:1239, y:533, w:100, h:103,
    name:'RWR azimuth indicator (ALR-67)' },
  { id:'rwrInt', view:'front', kind:'knob', x:1319, y:612, w:26, h:26,
    name:'RWR INT (intensity) knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'stbyAsi', view:'front', kind:'lamp', x:1100, y:649, w:64, h:64,
    name:'Standby airspeed indicator' },
  { id:'stbyAlt', view:'front', kind:'lamp', x:1186, y:649, w:67, h:65,
    name:'Standby barometric altimeter' },
  { id:'stbyVvi', view:'front', kind:'lamp', x:1279, y:647, w:67, h:67,
    name:'Vertical velocity indicator' },

  /* ===== PANELS · Landing Gear Panel =================================== */
  { id:'gearHandle', view:'front', kind:'lever', x:315, y:750, w:65, h:68,
    name:'Landing gear handle', states:['down','up'],
    lab:{up:'UP', down:'DOWN'}, init:'up' },
  { id:'downLockOride', view:'front', kind:'push', x:302, y:754, w:24, h:21,
    name:'DOWN LOCK ORIDE button', states:['norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'warnToneSil', view:'front', kind:'push', x:300, y:681, w:23, h:22,
    name:'WARN / TONE SIL button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'emergGear', view:'front', kind:'lever', x:310, y:556, w:76, h:60,
    name:'EMERG landing gear ROTATE AND PULL handle', states:['stowed','pulled'],
    lab:{stowed:'STOWED', pulled:'PULLED'}, init:'stowed' },

  /* ===== PANELS · Select Jettison & Brakes ============================= */
  { id:'launchBar', view:'front', kind:'sw', x:276, y:842, w:32, h:38,
    name:'LAUNCH BAR switch (RETRACT / EXTEND)', states:['extend','retract'],
    lab:{retract:'RETRACT', extend:'EXTEND'}, init:'retract' },
  { id:'flapSw', view:'front', kind:'sw', x:336, y:842, w:30, h:31,
    name:'FLAP switch (AUTO / HALF / FULL)', states:['full','half','auto'],
    lab:{auto:'AUTO', half:'HALF', full:'FULL'}, init:'auto' },
  { id:'selectJett', view:'front', kind:'knob', x:492, y:822, w:22, h:26,
    name:'SELECT JETT knob and JETT button', states:['safe','racklchr','stores','lfusmsl','rfusmsl'],
    lab:{safe:'SAFE', racklchr:'RACK/LCHR', stores:'STORES', lfusmsl:'L FUS MSL', rfusmsl:'R FUS MSL'}, init:'safe', angles:[0,55,110,-55,-110] },
  { id:'ldgTaxiLight', view:'front', kind:'sw', x:258, y:924, w:31, h:41,
    name:'LDG/TAXI LIGHT switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'antiSkid', view:'front', kind:'sw', x:326, y:913, w:33, h:38,
    name:'ANTI SKID switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'emergBrk', view:'front', kind:'lever', x:465, y:925, w:28, h:38,
    name:'EMERG BRK PULL handle', states:['stowed','pulled'],
    lab:{stowed:'STOWED', pulled:'PULLED'}, init:'stowed' },
  { id:'parkBrake', view:'front', kind:'lever', x:346, y:961, w:108, h:42,
    name:'PARKING BRAKE lever', states:['released','engaged'],
    lab:{engaged:'ENGAGED', released:'RELEASED'}, init:'engaged' },
  { id:'hookBypass', view:'front', kind:'sw', x:203, y:1013, w:30, h:36,
    name:'HOOK BYPASS switch (FIELD / CARRIER)', states:['carrier','field'],
    lab:{field:'FIELD', carrier:'CARRIER'}, init:'field' },
  { id:'brakePress', view:'front', kind:'lamp', x:287, y:994, w:72, h:72,
    name:'Hydraulic brake pressure gauge' },

  /* ===== PANELS · Hook & Wing Fold ===================================== */
  { id:'hookLever', view:'front', kind:'lever', x:1478, y:658, w:70, h:100,
    name:'ARRESTING HOOK lever', states:['down','up'],
    lab:{up:'UP', down:'DOWN'}, init:'up' },
  { id:'hookLight', tray:true, kind:'lamp', 
    name:'HOOK indicator light' },
  { id:'radarAlt', view:'front', kind:'lamp', x:1461, y:629, w:36, h:30,
    name:'Radar altimeter and warning index' },
  { id:'buno', view:'front', kind:'lamp', x:1484, y:860, w:75, h:51,
    name:'BUNO plate' },
  { id:'wingFold', view:'front', kind:'lever', axis:'x', x:1601, y:855, w:130, h:52,
    name:'WING FOLD handle (FOLD / SPREAD, PULL–PUSH to lock)', states:['fold','spread','spreadlocked'],
    lab:{fold:'FOLD', spread:'SPREAD', spreadlocked:'SPREAD & LOCKED'}, init:'fold' },
  { id:'landingChecklist', view:'front', kind:'lamp', x:1539, y:726, w:75, h:72,
    name:'LANDING checklist placard' },
  { id:'stbyCaution', view:'front', kind:'lamp', x:1170, y:114, w:128, h:50,
    name:'Standby caution panel' },
  { id:'avCool', view:'front', kind:'sw', x:1716, y:966, w:42, h:35,
    name:'AV COOL switch (NORM / EMERG)', states:['norm','emerg'],
    lab:{norm:'NORM', emerg:'EMERG'}, init:'norm' },
  { id:'hydPress', view:'front', kind:'lamp', x:1386, y:944, w:75, h:76,
    name:'Hydraulic pressure gauge (HYD 1 / HYD 2)' },

  /* ===== PANELS · Countermeasures ====================================== */
  { id:'ecmJett', view:'front', kind:'push', x:835, y:894, w:34, h:30,
    name:'ECM JETT button', states:['stowed','pressed'],
    lab:{stowed:'STOWED', pressed:'PRESSED'}, init:'stowed' },
  { id:'alr67Power', view:'front', kind:'push', x:916, y:867, w:21, h:16,
    name:'ALR-67 POWER button', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'cmdsDisType', view:'front', kind:'knob', x:911, y:904, w:27, h:28,
    name:'DIS TYPE knob (A / U / F / N / I)', states:['off','a','u','f','n','i'],
    lab:{off:'OFF', a:'A', u:'U', f:'F', n:'N', i:'I'}, init:'off', angles:[-120,-72,-24,24,72,120] },
  { id:'dispenser', view:'front', kind:'sw', x:840, y:982, w:22, h:40,
    name:'DISPENSER switch (ON / BYPASS / OFF)', states:['off','on','bypass'],
    lab:{off:'OFF', on:'ON', bypass:'BYPASS'}, init:'off' },
  { id:'ecmKnob', view:'front', kind:'knob', x:922, y:959, w:39, h:41,
    name:'ECM selector (OFF / STBY / BIT / REC / XMIT)', states:['off','stby','bit','rec','xmit'],
    lab:{off:'OFF', stby:'STBY', bit:'BIT', rec:'REC', xmit:'XMIT'}, init:'off', angles:[-125,-70,-15,40,95] },
  { id:'auxRel', tray:true, kind:'sw', 
    name:'AUX REL switch (NORM / ENABLE)', states:['norm','enable'],
    lab:{norm:'NORM', enable:'ENABLE'}, init:'norm' },
  { id:'cabinPressAlt', view:'front', kind:'lamp', x:979, y:919, w:34, h:35,
    name:'Cabin pressure altimeter' },

  /* ===== PANELS · Left Console — Power & Exterior Lights =============== */
  /* FIRE & BLEED AIR TEST: hidden behind the throttle grip in the idle
     photo, so it is a `peek` control — the left console swings to the
     throttle-aft photo while a step is working it. */
  { id:'fireTest', view:'lcon', peek:true, kind:'sw', axis:'x', x:1798, y:712, w:57, h:60,
    name:'FIRE & BLEED AIR TEST switch (TEST A / NORM / TEST B)', states:['testb','norm','testa'],
    lab:{norm:'NORM', testa:'TEST A', testb:'TEST B'}, init:'norm' },
  { id:'gndPwr1', view:'lcon', peek:true, kind:'sw', axis:'x', x:1664, y:578, w:52, h:65,
    name:'GND PWR 1 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr2', view:'lcon', kind:'sw', x:1628, y:534, w:59, h:40,
    name:'GND PWR 2 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr3', view:'lcon', kind:'sw', axis:'x', x:1565, y:578, w:51, h:65,
    name:'GND PWR 3 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'gndPwr4', view:'lcon', kind:'sw', x:1538, y:535, w:55, h:41,
    name:'GND PWR 4 switch (A ON / AUTO / B ON)', states:['bon','auto','aon'],
    lab:{auto:'AUTO', aon:'A ON', bon:'B ON'}, init:'auto' },
  { id:'extPwr', view:'lcon', kind:'sw', x:1504, y:583, w:62, h:41,
    name:'EXT PWR switch (RESET / NORM / OFF)', states:['off','norm','reset'],
    lab:{norm:'NORM', reset:'RESET', off:'OFF'}, init:'norm' },
  { id:'genTie', view:'lcon', kind:'lever', x:1298, y:424, w:58, h:66,
    name:'GEN TIE switch (NORM / RESET)', states:['norm','reset'],
    lab:{norm:'NORM', reset:'RESET'}, init:'norm' },
  { id:'formationLt', view:'lcon', kind:'knob', x:1401, y:565, w:66, h:54,
    name:'FORMATION lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'positionLt', view:'lcon', kind:'knob', x:1298, y:518, w:62, h:58,
    name:'POSITION lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  /* The photograph shows the STROBE knob clearly at the aft end of the
     exterior lights panel, so unlike the drawing days it has a home on the
     left console view. */
  { id:'strobeLt', view:'lcon', kind:'knob', x:1244, y:589, w:65, h:51,
    name:'STROBE lights switch (BRT / OFF / DIM)', states:['dim','off','brt'],
    lab:{dim:'DIM', off:'OFF', brt:'BRT'}, init:'off', angles:[-60,0,60] },

  /* ===== PANELS · Left Console — Engine, Fuel & FCS ==================== */
  { id:'apuSw', view:'lcon', kind:'sw', x:919, y:428, w:44, h:32,
    name:'APU switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'apuReady', view:'lcon', kind:'lamp', x:930, y:482, w:25, h:19,
    name:'APU READY light' },
  { id:'engCrank', view:'lcon', kind:'sw', axis:'x', x:789, y:445, w:39, h:44,
    name:'ENG CRANK switch (L / OFF / R)', states:['l','off','r'],
    lab:{off:'OFF', l:'L', r:'R'}, init:'off' },
  { id:'probeSw', view:'lcon', kind:'sw', x:968, y:549, w:30, h:41,
    name:'Refuelling PROBE switch (EXTEND / RETRACT / EMERG EXTD)', states:['emergextd','retract','extend'],
    lab:{retract:'RETRACT', extend:'EXTEND', emergextd:'EMERG EXTD'}, init:'retract' },
  { id:'extTankWing', view:'lcon', kind:'sw', x:1002, y:628, w:40, h:44,
    name:'EXT TANKS WING switch (ORIDE / NORM / STOP)', states:['stop','norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE', stop:'STOP'}, init:'norm' },
  { id:'extTankCtr', view:'lcon', kind:'sw', x:1004, y:708, w:42, h:43,
    name:'EXT TANKS CTR switch (ORIDE / NORM / STOP)', states:['stop','norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE', stop:'STOP'}, init:'norm' },
  { id:'fuelDump', view:'lcon', kind:'sw', x:949, y:770, w:52, h:44,
    name:'FUEL DUMP switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'toTrim', view:'lcon', kind:'push', x:792, y:552, w:58, h:60,
    name:'T/O TRIM button (and RUD TRIM knob)',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'fcsGain', view:'lcon', kind:'lever', x:764, y:674, w:122, h:41,
    name:'FCS GAIN switch (NORM / ORIDE)', states:['norm','oride'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'fcsReset', view:'lcon', kind:'push', x:806, y:771, w:48, h:49,
    name:'FCS RESET button',
    states:['out','in'],
    lab:{out:'\u2014', in:'PRESSED'}, init:'out' },
  { id:'volIcs', view:'lcon', kind:'knob', x:690, y:555, w:40, h:40,
    name:'ICS volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volWpn', view:'lcon', kind:'knob', x:682, y:628, w:45, h:44,
    name:'WPN volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volMidsA', view:'lcon', kind:'knob', x:678, y:700, w:45, h:44,
    name:'MIDS A volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volAux', view:'lcon', kind:'knob', x:674, y:774, w:44, h:44,
    name:'AUX volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },

  /* ===== PANELS · Left Console — Comm, IFF & Oxygen ==================== */
  { id:'antSelIff', view:'lcon', kind:'sw', axis:'x', x:562, y:452, w:43, h:49,
    name:'ANT SEL — IFF (UPPER / BOTH / LOWER)', states:['upper','both','lower'],
    lab:{both:'BOTH', upper:'UPPER', lower:'LOWER'}, init:'both' },
  { id:'antSelComm1', view:'lcon', kind:'sw', axis:'x', x:494, y:452, w:43, h:49,
    name:'ANT SEL — COMM 1 (UPPER / AUTO / LOWER)', states:['upper','auto','lower'],
    lab:{auto:'AUTO', upper:'UPPER', lower:'LOWER'}, init:'auto' },
  { id:'voxSw', view:'lcon', kind:'sw', axis:'x', x:598, y:552, w:40, h:46,
    name:'VOX / HOT MIC / COLD MIC switch', states:['vox','hotmic','coldmic'],
    lab:{coldmic:'COLD MIC', vox:'VOX', hotmic:'HOT MIC'}, init:'coldmic' },
  { id:'volRwr', view:'lcon', kind:'knob', x:585, y:628, w:46, h:44,
    name:'RWR volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volMidsB', view:'lcon', kind:'knob', x:579, y:700, w:46, h:44,
    name:'MIDS B volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'volTcn', view:'lcon', kind:'knob', x:570, y:778, w:46, h:40,
    name:'TCN volume knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'ufcSw', view:'lcon', kind:'sw', axis:'x', x:488, y:661, w:34, h:51,
    name:'UFC switch (ON / OFF)', states:['off','on'],
    lab:{on:'ON', off:'OFF'}, init:'on' },
  { id:'masterEmer', view:'lcon', kind:'sw', axis:'x', x:471, y:773, w:52, h:52,
    name:'MASTER radio switch (NORM / EMER)', states:['emer','norm'],
    lab:{norm:'NORM', emer:'EMER'}, init:'norm' },
  { id:'gXmt', view:'lcon', kind:'sw', axis:'x', x:416, y:566, w:46, h:50,
    name:'G XMT switch (COMM 1 / OFF / COMM 2)', states:['comm1','off','comm2'],
    lab:{off:'OFF', comm1:'COMM 1', comm2:'COMM 2'}, init:'off' },
  { id:'rlySw', view:'lcon', kind:'sw', axis:'x', x:339, y:566, w:50, h:50,
    name:'RLY switch (CIPHER / OFF / PLAIN)', states:['cipher','off','plain'],
    lab:{off:'OFF', cipher:'CIPHER', plain:'PLAIN'}, init:'off' },
  { id:'ilsChannel', view:'lcon', kind:'knob', x:329, y:652, w:79, h:81,
    name:'ILS CHANNEL knob (1–20)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'iffMode4', view:'lcon', kind:'sw', axis:'x', x:386, y:771, w:48, h:52,
    name:'IFF MODE 4 switch (DIS / AUD / OFF)', states:['dis','aud','off'],
    lab:{off:'OFF', dis:'DIS', aud:'AUD'}, init:'off' },
  { id:'crypto', view:'lcon', kind:'sw', axis:'x', x:298, y:773, w:48, h:52,
    name:'IFF CRYPTO switch (HOLD / NORM / ZERO)', states:['hold','norm','zero'],
    lab:{norm:'NORM', hold:'HOLD', zero:'ZERO'}, init:'norm' },
  { id:'obogs', view:'lcon', kind:'sw', axis:'x', x:264, y:524, w:46, h:61,
    name:'OBOGS switch (ON / OFF)', states:['on','off'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'oxyFlow', view:'lcon', kind:'knob', x:200, y:661, w:81, h:81,
    name:'OXY FLOW knob (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-50,50] },
  { id:'hydIsol', view:'lcon', kind:'sw', axis:'x', x:189, y:433, w:56, h:54,
    name:'HYD ISOL switch (NORM / ORIDE)', states:['oride','norm'],
    lab:{norm:'NORM', oride:'ORIDE'}, init:'norm' },
  { id:'mcSw', view:'lcon', kind:'sw', axis:'x', x:76, y:433, w:50, h:47,
    name:'MC switch (MC 1 OFF / MC 2 OFF)', states:['mc1off','norm','mc2off'],
    lab:{norm:'NORM', mc1off:'MC 1 OFF', mc2off:'MC 2 OFF'}, init:'norm' },

  /* ===== PANELS · Right Console — Electrical =========================== */
  { id:'battVolt', view:'rcon', kind:'lamp', x:478, y:472, w:99, h:84,
    name:'Battery voltage gauge' },
  { id:'lGen', view:'rcon', kind:'sw', x:580, y:519, w:56, h:55,
    name:'L GEN switch (NORM / OFF)', states:['off','norm'],
    lab:{norm:'NORM', off:'OFF'}, init:'norm' },
  { id:'battSw', view:'rcon', kind:'sw', x:626, y:415, w:60, h:64,
    name:'BATT switch (ON / OFF / ORIDE)', states:['oride','off','on'],
    lab:{off:'OFF', on:'ON', oride:'ORIDE'}, init:'off' },
  { id:'rGen', view:'rcon', kind:'sw', x:692, y:336, w:50, h:51,
    name:'R GEN switch (NORM / OFF)', states:['off','norm'],
    lab:{norm:'NORM', off:'OFF'}, init:'norm' },

  /* ===== PANELS · Right Console — ECS & Anti-Ice ======================= */
  { id:'ecsMode', view:'rcon', kind:'sw', x:671, y:547, w:64, h:66,
    name:'ECS MODE switch (AUTO / MAN / OFF-RAM)', states:['offram','man','auto'],
    lab:{auto:'AUTO', man:'MAN', offram:'OFF/RAM'}, init:'auto' },
  { id:'ecsTemp', view:'rcon', kind:'knob', x:724, y:439, w:76, h:78,
    name:'ECS TEMP knob (COLD / HOT)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-110,110] },
  { id:'cabinPressSw', view:'rcon', kind:'sw', x:780, y:369, w:49, h:53,
    name:'CABIN PRESS switch (NORM / DUMP / RAM-DUMP)', states:['ramdump','dump','norm'],
    lab:{norm:'NORM', dump:'DUMP', ramdump:'RAM/DUMP'}, init:'norm' },
  { id:'pitotHeat', view:'rcon', kind:'sw', x:802, y:621, w:44, h:44,
    name:'PITOT ANTI ICE switch (ON / AUTO)', states:['auto','on'],
    lab:{auto:'AUTO', on:'ON'}, init:'auto' },
  { id:'engAntiIce', view:'rcon', kind:'sw', x:840, y:549, w:39, h:42,
    name:'ENG ANTI ICE switch (ON / OFF / TEST)', states:['test','off','on'],
    lab:{off:'OFF', on:'ON', test:'TEST'}, init:'off' },
  { id:'bleedAir', view:'rcon', kind:'knob', x:871, y:421, w:75, h:78,
    name:'BLEED AIR knob (NORM / OFF / L OFF / R OFF / AUG PULL)', states:['norm','loff','roff','off'],
    lab:{norm:'NORM', loff:'L OFF', roff:'R OFF', off:'OFF'}, init:'norm', angles:[0,-95,95,175] },

  /* ===== PANELS · Right Console — Interior Lights ====================== */
  { id:'consolesLt', view:'rcon', kind:'knob', x:911, y:639, w:65, h:68,
    name:'CONSOLES lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'instPnlLt', view:'rcon', kind:'knob', x:958, y:553, w:56, h:61,
    name:'INST PNL lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'floodLt', view:'rcon', kind:'knob', x:999, y:469, w:62, h:62,
    name:'FLOOD lights knob (OFF / BRT)', states:['off','brt'],
    lab:{off:'OFF', brt:'BRT'}, init:'off', angles:[-50,50] },
  { id:'ltTest', view:'rcon', kind:'sw', x:1032, y:747, w:38, h:42,
    name:'LT TEST switch (TEST / OFF)', states:['off','test'],
    lab:{off:'OFF', test:'TEST'}, init:'off' },
  { id:'warnCautLt', view:'rcon', kind:'knob', x:1060, y:663, w:48, h:52,
    name:'WARN / CAUT brightness knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'chartLt', view:'rcon', kind:'knob', x:1105, y:575, w:36, h:43,
    name:'CHART light knob',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'ltMode', view:'rcon', kind:'sw', x:1135, y:488, w:54, h:60,
    name:'Lighting MODE switch (NITE / DAY)', states:['day','nvg'],
    lab:{day:'DAY', nvg:'NVG'}, init:'day' },

  /* ===== PANELS · Right Console — Defog & Windshield =================== */
  { id:'defog', view:'rcon', kind:'lever', x:1066, y:355, w:46, h:75,
    name:'DEFOG lever', states:['low','norm','high'],
    lab:{low:'LOW', norm:'NORM', high:'HIGH'}, init:'norm' },
  { id:'windshieldAntiIce', view:'rcon', kind:'sw', x:1243, y:438, w:55, h:52,
    name:'WINDSHIELD ANTI ICE switch', states:['rain','off','antiice'],
    lab:{rain:'RAIN', off:'OFF', antiice:'ANTI ICE'}, init:'off' },

  /* ===== PANELS · Right Console — Sensors ============================== */
  { id:'flirSw', view:'rcon', kind:'sw', x:1148, y:768, w:48, h:59,
    name:'FLIR switch (ON / STBY / OFF)', states:['off','stby','on'],
    lab:{off:'OFF', stby:'STBY', on:'ON'}, init:'off' },
  { id:'ltdr', view:'rcon', kind:'sw', x:1202, y:664, w:61, h:59,
    name:'LTD/R switch (ARM / SAFE)', states:['aft','safe','arm'],
    lab:{aft:'AFT', safe:'SAFE', arm:'ARM'}, init:'safe' },
  { id:'lstNflr', view:'rcon', kind:'sw', x:1221, y:582, w:52, h:50,
    name:'LST/NFLR switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off' },
  { id:'radarKnob', view:'rcon', kind:'knob', x:1240, y:780, w:105, h:88,
    name:'RADAR knob (OFF / STBY / OPR / PULL EMERG)', states:['off','stby','opr','emerg'],
    lab:{off:'OFF', stby:'STBY', opr:'OPR', emerg:'EMERG'}, init:'off', angles:[-120,-60,0,90] },
  { id:'insKnob', view:'rcon', kind:'knob', x:1309, y:608, w:78, h:79,
    name:'INS knob (OFF / CV / GND / NAV / IFA / GYRO / TEST)', states:['off','cv','gnd','nav','ifa','gyro','test'],
    lab:{off:'OFF', cv:'CV', gnd:'GND', nav:'NAV', ifa:'IFA', gyro:'GYRO', test:'TEST'}, init:'off', angles:[-135,-90,-45,20,65,115,155] },

  /* ===== PANELS · Right Console — KY-58 Secure Voice =================== */
  { id:'kyMode', view:'rcon', kind:'knob', x:1395, y:845, w:96, h:95,
    name:'KY-58 MODE knob (P / C / LD / RV)', states:['p','c','ld','rv'],
    lab:{p:'P', c:'C', ld:'LD', rv:'RV'}, init:'p', angles:[-90,-30,30,90] },
  { id:'kyFill', view:'rcon', kind:'knob', x:1452, y:665, w:102, h:100,
    name:'KY-58 FILL selector (1–6 / Z 1-5 / ALL)',
    states:['min','set'],
    lab:{min:'\u2014', set:'SET'}, init:'min', angles:[-50,50] },
  { id:'kyVolume', view:'rcon', kind:'knob', x:1530, y:904, w:88, h:90,
    name:'KY-58 VOLUME knob',
    states:['down','up'],
    lab:{down:'DOWN', up:'UP'}, init:'down', angles:[-50,50] },
  { id:'kyTd', view:'rcon', kind:'knob', x:1588, y:730, w:55, h:60,
    name:'KY-58 TD switch (ON / OFF)', states:['off','on'],
    lab:{off:'OFF', on:'ON'}, init:'off', angles:[-50,50] },

  /* ===== NOT IN ANY VIEW ================================================
     Hand controls and the canopy: real, needed by the start-up model, and not
     drawn on a panel layout. That is what `tray` is for. */
  { id:'throttleL', tray:true, kind:'lever', name:'LEFT THROTTLE',
    states:['off','idle','mil','max'],
    lab:{off:'OFF', idle:'IDLE', mil:'MIL', max:'MAX'}, init:'off' },
  { id:'throttleR', tray:true, kind:'lever', name:'RIGHT THROTTLE',
    states:['off','idle','mil','max'],
    lab:{off:'OFF', idle:'IDLE', mil:'MIL', max:'MAX'}, init:'off' },
  { id:'canopy', tray:true, kind:'lever', name:'CANOPY HANDLE',
    states:['open','closed'], lab:{open:'OPEN', closed:'CLOSED'}, init:'open' },
  { id:'ejectSeat', tray:true, kind:'lever', name:'EJECTION SEAT HANDLE',
    states:['safe','armed'], lab:{safe:'SAFE', armed:'ARMED'}, init:'safe' },
  { id:'harness', tray:true, kind:'lever', name:'HARNESS LOCK LEVER',
    states:['unlocked','locked'], lab:{unlocked:'UNLOCKED', locked:'LOCKED'}, init:'unlocked' },
  { id:'fingerLifts', tray:true, kind:'lever', name:'THROTTLE FINGER LIFTS',
    states:['down','up'], lab:{down:'DOWN', up:'UP'}, init:'down' },
  { id:'hudGlass', tray:true, kind:'lamp', name:'HUD combiner glass' },
];
