/* ============================================================
   F/A-18C HORNET · COLD START
   Cold and dark to ready to taxi

   Chuck's guide, PART 4 — START-UP PROCEDURE

   GENERATED from the procedure tables. done(s) is evaluated every frame, so a
   step ticks itself off when the aircraft actually reaches that state rather
   than when you claim it has.
   ============================================================ */
import { stamp } from './_common.js';

export const meta = { id:'cold-start', crew:'pilot', phase:'startup', variant:'shore',
                      name:'Cold start', view:'front',
                      ending:{ title:'Ready to Taxi', sub:'Brake off, lights on, cleared to move.' } };

export const steps = stamp([
  {g:'1 · Before power', t:'Ejection seat lever — DOWN and ARMED, harness lever — FORWARD',
   note:'Not on this layout: it is down beside your left thigh. An unarmed seat is the CK SEAT caption on the standby panel, and the one item on this list that cannot be fixed in the air.', ack:true},
  {g:'1 · Before power', t:'Parking brake — ENGAGED',
   note:'A cold Hornet is found with the brake already out. Confirm it rather than assume it — you are about to bring 8,000 lb of thrust online.',
   tgt:'parkBrake', done:s=>s.sw.parkBrake==='engaged'},
  {g:'1 · Before power', t:'MASTER ARM — SAFE',
   note:'Third item, before anything is powered, because after this the jet starts getting electricity.',
   tgt:'masterArm', done:s=>s.sw.masterArm==='safe'},
  {g:'2 · Battery on', t:'BATT switch — ON',
   note:'Right-click to ON. This is the moment the jet wakes: engine igniters, canopy and the IFEI come alive. Everything before this was mechanical.',
   tgt:'battSw', done:s=>s.sw.battSw==='on'},
  {g:'2 · Battery on', t:'Hydraulic brake pressure — CHECK 3,000 psi minimum',
   note:'The accumulator holds this with both engines off. Below 3,000 you have one or two applications of brake and then nothing, which on a carrier deck is a very short conversation.',
   tgt:'brakePress', done:s=>s.brakePsi>=3000},
  {g:'2 · Battery on', t:'FIRE & BLEED AIR TEST — hold to TEST A (channel A)',
   note:'Hold it until the whole aural sequence finishes — left fire, right fire, APU fire, both bleeds. It springs back on release. Optional in DCS; not optional in a real cockpit.',
   tgt:'fireTest', done:s=>s.sw.fireTest==='testa'},
  {g:'2 · Battery on', t:'BATT switch — cycle OFF and back ON (rewinds the test tape)',
   note:'Or just wait ten seconds — the warning audio is literally a tape and has to spool back before channel B will play. Leave it ON: with the battery off nothing downstream works, and the APU will sit there refusing to spool with no caution to tell you why.',
   tgt:'battSw', done:s=>s.sw.battSw==='on'},
  {g:'2 · Battery on', t:'FIRE & BLEED AIR TEST — hold to TEST B (channel B)',
   note:'Same again for detection loop B. Note that this test has now closed both engine bleed air valves — you will re-open them later, and if you forget, the ECS never comes on.',
   tgt:'fireTest', done:s=>s.sw.fireTest==='testb'},
  {g:'3 · APU and the right engine', t:'Standby caution panel — no APU ACC caution',
   note:'Nine captions, and on battery alone they are the only cautions you have. APU ACC lit before you start means the accumulator has not charged and the APU will not spin.',
   tgt:'stbyCaution', ack:true},
  {g:'3 · APU and the right engine', t:'APU switch — ON',
   note:'Forward. The auxiliary power unit is what turns the engines; there is no other air source on a carrier deck.',
   tgt:'apuSw', done:s=>s.sw.apuSw==='on'},
  {g:'3 · APU and the right engine', t:'APU READY light — WAIT for green',
   note:'Cranking before the APU is up gives you a slow, hot start. In real life the plane captain tells you; in DCS you listen for the spool.',
   tgt:'apuReady', done:s=>s.apu.ready},
  {g:'3 · APU and the right engine', t:'ENG CRANK — R (right engine first)',
   note:'Right first, always. The right engine drives most of the hydraulic pressure for the brakes, and you would rather have brakes early than late.',
   tgt:'engCrank', done:s=>s.sw.engCrank==='r'},
  {g:'3 · APU and the right engine', t:'At 25% RPM — right throttle OFF to IDLE',
   note:'This opens the fuel valves. Too early and there is not enough airflow to light cleanly; too late and the starter runs out of air. 25% is the number.',
   key:'RSHIFT + HOME', ack:true},
  {g:'3 · APU and the right engine', t:'EGT below 750 °C, right RPM stabilised 60–65%, R GEN caution out',
   note:'The generator caption going out is your confirmation the engine is actually making electricity, not just noise.', ack:true},
  {g:'4 · Displays', t:'MASTER CAUTION — RESET',
   note:'You will press this several more times. Twice in a row re-stacks the caution list so a DDI page underneath becomes readable.',
   tgt:'masterCaution', done:s=>s.sw.masterCaution==='in'},
  {g:'4 · Displays', t:'Left DDI brightness — DAY',
   note:'This knob is the DDI power switch. There is no separate one.',
   tgt:'ddiLBright', done:s=>s.sw.ddiLBright==='day'},
  {g:'4 · Displays', t:'Right DDI brightness — DAY',
   tgt:'ddiRBright', done:s=>s.sw.ddiRBright==='day'},
  {g:'4 · Displays', t:'AMPCD brightness — turn RIGHT to power it',
   note:'The moving map between your knees. You need it up before the INS alignment starts, because that is where the alignment quality is displayed.',
   tgt:'ampcdBright', done:s=>s.sw.ampcdBright==='brt'},
  {g:'4 · Displays', t:'HUD symbology brightness — turn RIGHT to power the HUD',
   tgt:'hudBright', done:s=>s.sw.hudBright==='on'},
  {g:'4 · Displays', t:'BLK LVL knob — turn RIGHT',
   tgt:'blkLvl', done:s=>s.sw.blkLvl==='set'},
  {g:'4 · Displays', t:'ALT switch — RDR',
   note:'Radar altimeter as the HUD reference. Height above the water is the number that matters in the pattern; height above sea level is not.',
   tgt:'altSw', done:s=>s.sw.altSw==='rdr'},
  {g:'4 · Displays', t:'ATT switch — AUTO',
   tgt:'attSw', done:s=>s.sw.attSw==='auto'},
  {g:'5 · INS alignment', t:'BLEED AIR knob — rotate a full turn back to NORM',
   note:'The fire test closed both valves. A full 360° clockwise back to NORM re-opens them; you will hear the ECS kick in. Skip this and the cockpit never pressurises.',
   tgt:'bleedAir', done:s=>!s.bleedClosed},
  {g:'5 · INS alignment', t:'Canopy — CLOSE',
   note:'The canopy control is on the left canopy sill, not on this layout. Leave it open a moment longer if you still need to talk to the deck crew.', ack:true},
  {g:'5 · INS alignment', t:'INS knob — CV (carrier) or GND (ashore)',
   note:'CV takes the alignment position straight off the ship through the SINS cable, which is the only way to align a moving platform. Ashore it is GND.',
   tgt:'insKnob', done:s=>s.sw.insKnob==='cv'},
  {g:'6 · FCS and the left engine', t:'AMPCD — monitor GRND QUAL until it reads OK',
   note:'Eight minutes for a normal alignment, about ninety seconds if you take the stored heading from the HSI page. The countdown is in seconds.',
   tgt:'ampcd', done:s=>s.ins.complete},
  {g:'6 · FCS and the left engine', t:'INS knob — IFA once aligned (NAV if the mission predates GPS)',
   note:'IFA blends GPS with the inertial platform and stops the drift. You will see POS/AINS on the HSI when it takes.',
   tgt:'insKnob', done:s=>s.sw.insKnob==='ifa'},
  {g:'6 · FCS and the left engine', t:'Left DDI — select the FCS page (MENU → SUPT → FCS)',
   tgt:'ddiL', done:s=>s.sw.ddiLBright!=='off'},
  {g:'6 · FCS and the left engine', t:'FCS RESET — PRESS',
   note:'The Xs on the FCS page are almost always wing droop from the jet sitting parked. One press clears them.',
   tgt:'fcsReset', done:s=>s.sw.fcsReset==='in'},
  {g:'6 · FCS and the left engine', t:'LT TEST — HOLD and check every caption lights',
   note:'A caution light that does not work is worse than no caution light, because you will believe it.',
   tgt:'ltTest', done:s=>s.sw.ltTest==='test'},
  {g:'6 · FCS and the left engine', t:'ENG CRANK — L (left engine)',
   tgt:'engCrank', done:s=>s.sw.engCrank==='l'},
  {g:'7 · Configure for taxi', t:'At 25% RPM — left throttle OFF to IDLE',
   note:'A different modifier from the right engine. Getting this wrong is the single most common start-up error.',
   key:'RALT + HOME', ack:true},
  {g:'7 · Configure for taxi', t:'Left engine stabilised, L GEN caution out, APU shuts down automatically',
   note:'About a minute after both engines settle, the APU stops on its own. You do not switch it off.', ack:true},
  {g:'7 · Configure for taxi', t:'OBOGS — ON',
   note:'On-board oxygen. Forget it and nothing happens at all until you are high, at which point quite a lot happens.',
   tgt:'obogs', done:s=>s.sw.obogs==='on'},
  {g:'7 · Configure for taxi', t:'HOOK BYPASS — CARRIER (FIELD ashore)',
   note:'In FIELD the hook will not retract automatically after a trap, so you sit on the wire holding up the recovery.',
   tgt:'hookBypass', done:s=>s.sw.hookBypass==='carrier'},
  {g:'7 · Configure for taxi', t:'FLAP switch — HALF',
   note:'HALF for the cat shot. FULL is for landing.',
   tgt:'flapSw', done:s=>s.sw.flapSw==='half'},
  {g:'7 · Configure for taxi', t:'ANTI SKID — OFF at the boat (ON ashore)',
   note:'Backwards from what you would guess. On the deck you want the wheels locked when the hook grabs, not modulated.',
   tgt:'antiSkid', done:s=>s.sw.antiSkid==='off'},
  {g:'7 · Configure for taxi', t:'RADAR knob — OPERATE',
   note:'Safe on the ground: radiation is inhibited with weight on wheels, so nothing is being cooked on the deck.',
   tgt:'radarKnob', done:s=>s.sw.radarKnob==='opr'},
  {g:'8 · Avionics', t:'Right DDI — run the FCS BIT (BIT page → FCS-MC → hold Y → FCS)',
   note:'Hold the Y binding to hold the FCS BIT switch up, then press the FCS option. The control surfaces will move on their own for the duration — expected, and worth watching once.',
   key:'Y',
   tgt:'ddiR', done:s=>s.sw.ddiRBright!=='off'},
  {g:'8 · Avionics', t:'T/O TRIM button — PRESS',
   note:'Sets the stabilators nose-up for take-off. At the boat you then add more by weight: 16° up to 44,000 lb, 17° to 48,000, 19° above.',
   tgt:'toTrim', done:s=>s.sw.toTrim==='in'},
  {g:'8 · Avionics', t:'PITOT ANTI ICE — AUTO',
   note:'AUTO inhibits pitot heat on the ground so full thrust is available off the cat. ON is for actual icing, and costs you power.',
   tgt:'pitotHeat', done:s=>s.sw.pitotHeat==='auto'},
  {g:'8 · Avionics', t:'WING FOLD — leave FOLDED at the boat (SPREAD and locked ashore)',
   note:'Taxi folded on a carrier — the deck is 250 ft wide and full of other aeroplanes. You spread on the catapult when the director tells you.',
   tgt:'wingFold', done:s=>s.sw.wingFold==='fold'},
  {g:'8 · Avionics', t:'Radar altimeter warning index — SET 80 ft (200 ft ashore)',
   tgt:'radarAlt', ack:true},
  {g:'8 · Avionics', t:'Standby attitude indicator — UNCAGE',
   note:'The red OFF flag disappears. This is your last attitude reference if both DDIs and the HUD go, so it is worth the two seconds.',
   tgt:'stbyAdiCage', done:s=>s.sw.stbyAdiCage==='uncaged'},
  {g:'8 · Avionics', t:'BINGO fuel — SET on the IFEI (8,000 lb is a reasonable default)',
   note:'Up and down arrows on the IFEI. BINGO is the fuel at which you stop doing whatever you are doing and go home.',
   tgt:'ifeiUp', done:s=>s.sw.ifeiUp==='in'},
  {g:'8 · Avionics', t:'ALR-67 POWER — PRESS',
   note:'Radar warning receiver. Nothing at all appears on the azimuth indicator until this button is in.',
   tgt:'alr67Power', done:s=>s.sw.alr67Power==='on'},
  {g:'8 · Avionics', t:'ECM selector — STBY',
   tgt:'ecmKnob', done:s=>s.sw.ecmKnob==='stby'},
  {g:'9 · Lights and chocks', t:'DISPENSER switch — ON (middle position)',
   note:'Middle is ON, which is not obvious. It is on the landing checklist placard too, because chaff on the deck is a bad day for the deck crew.',
   tgt:'dispenser', done:s=>s.sw.dispenser==='on'},
  {g:'9 · Lights and chocks', t:'UFC — IFF, then hold ON/OFF to power it',
   note:'Hold the ON button a couple of seconds. "XP" on the scratchpad means it took. Check Mode 4A shows a colon beside it.',
   tgt:'ufcIFF', done:s=>s.sw.ufcIFF==='in'},
  {g:'9 · Lights and chocks', t:'UFC — D/L twice for Link-16, then hold ON/OFF',
   note:'First press is Link-4, second is Link-16. Default frequency 127 is fine.',
   tgt:'ufcDL', done:s=>s.sw.ufcDL==='in'},
  {g:'9 · Lights and chocks', t:'Audio panel — MIDS A and MIDS B volumes UP',
   note:'Easy to miss and completely silent when wrong. Datalink voice comes through these two.',
   tgt:'volMidsA', done:s=>s.sw.volMidsA==='up'},
  {g:'9 · Lights and chocks', t:'HMD brightness — BRT if wearing the JHMCS',
   tgt:'hmdKnob', done:s=>s.sw.hmdKnob==='brt'},
  {g:'9 · Lights and chocks', t:'STROBE lights — ON',
   tgt:'strobeLt', done:s=>s.sw.strobeLt==='brt'},
  {g:'9 · Lights and chocks', t:'POSITION lights — BRT',
   tgt:'positionLt', done:s=>s.sw.positionLt==='brt'},
  {g:'9 · Lights and chocks', t:'FORMATION lights — BRT',
   tgt:'formationLt', done:s=>s.sw.formationLt==='brt'},
  {g:'9 · Lights and chocks', t:'LDG / TAXI light — ON',
   tgt:'ldgTaxiLight', done:s=>s.sw.ldgTaxiLight==='on'},
  {g:'9 · Lights and chocks', t:'Parking brake — RELEASE (push it in)',
   note:'Last item, deliberately. Everything before this could be done with the jet immobile.',
   tgt:'parkBrake', done:s=>s.sw.parkBrake==='released'},
]);
