/* ============================================================
   F-14B · CONTROLS
   Coordinates are pixels in the 1920x1080 space of each photo.
   Anything marked (est) was placed by feature detection without
   visual confirmation — check those first in Calibrate mode.

   view    'front' | 'consoles'      pilot
           'pilotBoth'               the centre panel, in both pilot photos
           'rioL' | 'rioC' | 'rioR'  RIO
           tray:true                 not visible in any photo
   states  listed bottom-to-top, so a left-click moves the switch
           up / forward. updir:false where the panel reads the other way.
   ============================================================ */

export const controls = [

  /* ================= PILOT · armament panel (in both pilot photos) ========= */
  { id:'gunRate', view:'pilotBoth', kind:'sw', x:874, y:48, w:36, h:44,
    name:'GUN RATE', states:['low','high'], lab:{high:'HIGH',low:'LOW'}, init:'low' },
  { id:'swCool', view:'pilotBoth', kind:'sw', x:942, y:47, w:34, h:46,
    name:'SW COOL', states:['off','on'], lab:{on:'ON',off:'OFF'}, init:'off' },
  { id:'mslPrep', view:'pilotBoth', kind:'sw', x:1011, y:46, w:34, h:46,
    name:'MSL PREP', states:['off','on'], lab:{on:'ON',off:'OFF'}, init:'off' },
  { id:'masterArm', view:'pilotBoth', kind:'lever', x:1174, y:16, w:46, h:98,
    name:'MASTER ARM', states:['tng','off','on'], lab:{on:'ON',off:'OFF',tng:'TNG'}, init:'off' },
  { id:'modeStp', view:'pilotBoth', kind:'sw', x:1107, y:132, w:45, h:41,
    name:'MISSILE MODE/STP', states:['brsit','norm'], lab:{norm:'NORM',brsit:'BRSIT'}, init:'norm' },
  { id:'masterCaution', view:'pilotBoth', kind:'lamp', x:919, y:118, w:85, h:21,
    name:'MASTER CAUTION', color:'amber', watch:'masterCaution' },

  /* ================= PILOT · front panel ================================== */
  { id:'parkBrake', view:'front', kind:'lever', x:22, y:857, w:102, h:88, updir:false,
    name:'PARKING BRAKE', states:['off','set'], lab:{off:'RELEASED',set:'ENGAGED'}, init:'set' },
  { id:'gearHandle', view:'front', kind:'lever', x:210, y:738, w:46, h:60,
    name:'LANDING GEAR', states:['down','up'], lab:{down:'DOWN',up:'UP'}, init:'down' },
  { id:'radAltKnob', view:'front', kind:'knob', x:232, y:582, w:34, h:34,
    name:'RADAR ALTIMETER', states:['off','on'], lab:{off:'OFF',on:'BIT'}, init:'off' },
  { id:'stbyAdi', view:'front', kind:'knob', x:1371, y:389, w:38, h:38,
    name:'STANDBY ADI CAGE', states:['caged','erect'], lab:{caged:'CAGED',erect:'ERECT'}, init:'caged' },
  { id:'antiSkid', view:'front', kind:'sw', x:614, y:1000, w:36, h:48,
    name:'ANTI-SKID / SPOILER BK', states:['spoiler','off','both'],
    lab:{both:'BOTH',off:'OFF',spoiler:'SPLR BK'}, init:'both' },
  { id:'wingExtTrans', view:'front', kind:'sw', x:260, y:1013, w:36, h:52,
    name:'WING/EXT TRANS', states:['off','auto','oride'],
    lab:{oride:'ORIDE',auto:'AUTO',off:'OFF'}, init:'auto' },
  { id:'masterReset', view:'front', kind:'push', x:684, y:1033, w:32, h:32,
    name:'MASTER RESET', states:['out','in'], lab:{out:'—',in:'PRESSED'}, init:'out' },

  /* displays panel — the left column is the master mode buttons, not a mode knob */
  { id:'masterMode', view:'front', kind:'push', x:1651, y:762, w:38, h:184, stack:'v',
    name:'DISPLAY MASTER MODE', states:['to','cruise','aa','ag','ldg'],
    lab:{to:'T.O.',cruise:'CRUISE',aa:'A/A',ag:'A/G',ldg:'LDG'}, init:'to' },
  { id:'hudDeclutter', view:'front', kind:'sw', x:1713, y:792, w:36, h:34,
    name:'HUD DECLUTTER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hudAwl', view:'front', kind:'sw', x:1778, y:792, w:36, h:34,
    name:'HUD AWL MODE', states:['acl','ils'], lab:{ils:'ILS',acl:'ACL'}, init:'ils' },
  { id:'vdiMode', view:'front', kind:'sw', x:1711, y:852, w:36, h:34,
    name:'VDI MODE', states:['norm','tv'], lab:{norm:'NORM',tv:'TV'}, init:'norm' },
  { id:'vdiAwl', view:'front', kind:'sw', x:1770, y:854, w:36, h:34,
    name:'VDI AWL MODE', states:['acl','ils'], lab:{ils:'ILS',acl:'ACL'}, init:'ils' },
  { id:'hsdMode', view:'front', kind:'sw', x:1712, y:888, w:36, h:34,
    name:'HSD MODE', states:['tid','nav'], lab:{nav:'NAV',tid:'TID'}, init:'nav' },
  { id:'hsdEcm', view:'front', kind:'sw', x:1779, y:919, w:36, h:28,
    name:'HSD ECM', states:['off','oride'], lab:{oride:'ORIDE',off:'OFF'}, init:'off' },
  { id:'vdiPower', view:'front', kind:'sw', x:1649, y:948, w:36, h:48,
    name:'VDI POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hudPower', view:'front', kind:'sw', x:1714, y:948, w:36, h:48,
    name:'HUD POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hsdPower', view:'front', kind:'sw', x:1781, y:948, w:36, h:48,
    name:'HSD POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },

  /* ================= PILOT · consoles ===================================== */
  { id:'throttleL', view:'consoles', kind:'lever', x:396, y:150, w:46, h:170,
    name:'LEFT THROTTLE', states:['off','idle','mil'],
    lab:{off:'CUTOFF',idle:'IDLE',mil:'MIL'}, init:'off' },
  { id:'throttleR', view:'consoles', kind:'lever', x:450, y:150, w:46, h:170,
    name:'RIGHT THROTTLE', states:['off','idle','mil'],
    lab:{off:'CUTOFF',idle:'IDLE',mil:'MIL'}, init:'off' },
  { id:'wingSweep', view:'consoles', kind:'lever', x:572, y:100, w:28, h:252,
    name:'EMERG WING SWEEP HANDLE', states:['oversweep','fwd','detent'],
    lab:{oversweep:'OVERSWEEP 68°',fwd:'FWD 20° (raised)',detent:'FWD 20° · IN DETENT'},
    init:'oversweep' },
  { id:'engCrank', view:'consoles', kind:'sw', axis:'x', x:106, y:128, w:76, h:34,
    name:'ENGINE CRANK', states:['left','off','right'],
    lab:{left:'L',off:'OFF',right:'R'}, init:'off', spring:true },
  { id:'oxygen', view:'consoles', kind:'sw', x:540, y:980, w:38, h:50,
    name:'OXYGEN', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'ics', view:'consoles', kind:'sw', x:288, y:812, w:36, h:42,
    name:'ICS (INTERCOM)', states:['cold','hot'], lab:{cold:'COLD MIC',hot:'HOT MIC'}, init:'cold' },
  { id:'afcsPitch', view:'consoles', kind:'sw', x:93, y:543, w:34, h:58,
    name:'SAS PITCH', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'afcsRoll', view:'consoles', kind:'sw', x:178, y:543, w:34, h:58,
    name:'SAS ROLL', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'afcsYaw', view:'consoles', kind:'sw', x:261, y:543, w:34, h:58,
    name:'SAS YAW', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'uhfFunc', view:'consoles', kind:'knob', x:594, y:614, w:46, h:48, reverse:true,
    name:'UHF 1 FUNCTION (ARC-159)', states:['off','main','both'],
    lab:{off:'OFF',main:'MAIN',both:'BOTH'}, init:'off' },
  { id:'tacanFunc', view:'consoles', kind:'knob', x:588, y:810, w:52, h:60, reverse:true,
    name:'TACAN FUNCTION', states:['off','rec','tr','aa','bcn'],
    lab:{off:'OFF',rec:'REC',tr:'T/R',aa:'A/A',bcn:'BCN'}, init:'off' },
  { id:'masterGenL', view:'consoles', kind:'sw', x:1311, y:489, w:36, h:52,
    name:'L MASTER GEN', states:['test','off','norm'],
    lab:{norm:'NORM',off:'OFF/RST',test:'TEST'}, init:'norm' },
  { id:'masterGenR', view:'consoles', kind:'sw', x:1391, y:489, w:36, h:52,
    name:'R MASTER GEN', states:['test','off','norm'],
    lab:{norm:'NORM',off:'OFF/RST',test:'TEST'}, init:'norm' },
  { id:'airSource', view:'consoles', kind:'push', x:1502, y:638, w:40, h:208, stack:'v',
    name:'AIR SOURCE', states:['ram','leng','reng','both','off'],
    lab:{ram:'RAM',leng:'L ENG',reng:'R ENG',both:'BOTH ENG',off:'OFF'}, init:'off' },
  { id:'hydTransfer', view:'consoles', kind:'lever', x:1399, y:974, w:36, h:92, updir:false,
    name:'HYD TRANSFER PUMP', states:['shutoff','norm'],
    lab:{norm:'NORM',shutoff:'SHUTOFF'}, init:'norm' },
  { id:'emergFltHyd', view:'consoles', kind:'lever', x:1851, y:855, w:36, h:106,
    name:'EMERG FLIGHT HYD', states:['autolow','low','high'],
    lab:{autolow:'AUTO / LOW',low:'LOW',high:'HIGH'}, init:'autolow' },
  { id:'ara63', view:'consoles', kind:'sw', x:1830, y:317, w:36, h:42,
    name:'ARA-63 ICLS POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'extLights', view:'consoles', kind:'sw', x:1650, y:464, w:32, h:44,
    name:'POSITION LIGHTS', states:['dim','off','brt'],
    lab:{dim:'DIM',off:'OFF',brt:'BRT'}, init:'off' },

  /* caution / advisory capsules. 4 columns at 1348.5/1412.5/1477/1541.5,
     13 caption rows starting at y=188 with roughly 20px pitch. */
  { id:'clStartValve', view:'consoles', kind:'lamp', x:1511, y:220, w:61, h:17,
    name:'START VALVE', color:'amber', watch:'startValve' },
  { id:'clOilPress', view:'consoles', kind:'lamp', x:1446, y:259, w:61, h:17,
    name:'OIL PRESS', color:'red', watch:'oilPress' },
  { id:'clLGen', view:'consoles', kind:'lamp', x:1318, y:298, w:61, h:17,
    name:'L GEN', color:'amber', watch:'lGen' },
  { id:'clRGen', view:'consoles', kind:'lamp', x:1382, y:298, w:61, h:17,
    name:'R GEN', color:'amber', watch:'rGen' },
  { id:'clCanopy', view:'consoles', kind:'lamp', x:1446, y:298, w:61, h:17,
    name:'CANOPY', color:'amber', watch:'canopy' },
  { id:'clHydPress', view:'consoles', kind:'lamp', x:1511, y:321, w:61, h:17,
    name:'HYD PRESS', color:'amber', watch:'hydPress' },

  /* ================= not visible in any photo ============================= */
  { id:'ejectSeat', tray:true, kind:'lever', name:'EJECTION SEAT',
    states:['safe','armed'], lab:{safe:'SAFE',armed:'ARMED'}, init:'safe' },
  { id:'canopy', tray:true, kind:'lever', name:'CANOPY',
    states:['open','closed'], lab:{open:'OPEN',closed:'CLOSED'}, init:'open' },

  /* ================= RIO · left console =================================== */
  /* CAP keyboard. Grid taken from the printed legends: columns at
     398/444/492/540/588, rows at 101/145/192. */
  { id:'capClear', view:'rioL', kind:'push', x:382, y:86, w:44, h:30,
    name:'CAP CLEAR', states:['out','in'], lab:{out:'CLEAR',in:'CLEAR'}, init:'out' },
  { id:'capSW', view:'rioL', kind:'push', x:462, y:86, w:32, h:30,
    name:'CAP S / W', states:['out','in'], lab:{out:'S-W',in:'S-W'}, init:'out' },
  { id:'capNE', view:'rioL', kind:'push', x:508, y:86, w:32, h:30,
    name:'CAP N / E', states:['out','in'], lab:{out:'N-E',in:'N-E'}, init:'out' },
  { id:'capEnter', view:'rioL', kind:'push', x:574, y:86, w:48, h:30,
    name:'CAP ENTER', states:['out','in'], lab:{out:'ENTER',in:'ENTER'}, init:'out' },
  ...capKey('cap1', 377, 129, '1 · LAT'),  ...capKey('cap2', 423, 129, '2 · NPR'),
  ...capKey('cap3', 471, 129, '3 · SPD'),  ...capKey('cap4', 519, 129, '4 · ALT'),
  ...capKey('cap5', 567, 129, '5 · RNG'),  ...capKey('cap6', 377, 176, '6 · LONG'),
  ...capKey('cap7', 423, 176, '7'),        ...capKey('cap8', 471, 176, '8 · HDG'),
  ...capKey('cap9', 519, 176, '9'),        ...capKey('cap0', 567, 176, '0 · BRG'),

  /* CAP message select buttons — two columns of five, Hough-measured */
  { id:'msgOwnAC', view:'rioL', kind:'lamp', x:358, y:254, w:32, h:32,
    name:'OWN A/C', color:'green', watch:'msgOwnAC' },
  { id:'msgStoredHdg', view:'rioL', kind:'lamp', x:360, y:290, w:32, h:32,
    name:'STORED HDG ALIGN', color:'green', watch:'none' },
  { id:'msgTarpsNav', view:'rioL', kind:'lamp', x:357, y:331, w:32, h:32,
    name:'TARPS NAV FIX', color:'green', watch:'none' },
  { id:'msgWindSpd', view:'rioL', kind:'lamp', x:359, y:368, w:32, h:32,
    name:'WIND SPD HDG', color:'green', watch:'none' },
  { id:'msgTarps', view:'rioL', kind:'lamp', x:360, y:404, w:32, h:32,
    name:'TARPS', color:'green', watch:'none' },
  { id:'msgTacanFix', view:'rioL', kind:'lamp', x:595, y:263, w:32, h:32,
    name:'TACAN FIX', color:'green', watch:'none' },
  { id:'msgRdrFix', view:'rioL', kind:'lamp', x:595, y:296, w:32, h:32,
    name:'RDR FIX', color:'green', watch:'none' },
  { id:'msgVisFix', view:'rioL', kind:'lamp', x:596, y:333, w:32, h:32,
    name:'VIS FIX', color:'green', watch:'none' },
  { id:'msgFixEnable', view:'rioL', kind:'lamp', x:595, y:367, w:32, h:32,
    name:'FIX ENABLE', color:'green', watch:'none' },
  { id:'msgMagVar', view:'rioL', kind:'push', x:595, y:404, w:32, h:32,
    name:'MAG VAR HDG', states:['out','in'], lab:{out:'MAG VAR',in:'MAG VAR'}, init:'out' },

  { id:'capCategory', view:'rioL', kind:'knob', x:467, y:472, w:56, h:56,
    name:'CAP CATEGORY', states:['nav','tacdata','spl','dl','bit','tgtdata'],
    lab:{nav:'NAV',tacdata:'TAC DATA',spl:'SPL',dl:'D/L',bit:'BIT',tgtdata:'TGT DATA'}, init:'nav' },
  { id:'liquidCool', view:'rioL', kind:'sw', x:6, y:262, w:34, h:44,
    name:'LIQUID COOLING (est)', states:['off','fwd'], lab:{off:'OFF',fwd:'FWD / ON'}, init:'off' },
  { id:'rioIcs', view:'rioL', kind:'sw', x:592, y:760, w:34, h:46,
    name:'RIO ICS (est)', states:['cold','hot'], lab:{cold:'COLD MIC',hot:'HOT MIC'}, init:'cold' },
  { id:'rioOxygen', view:'rioL', kind:'sw', x:392, y:996, w:32, h:44,
    name:'RIO OXYGEN (est)', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'vuhfFunc', view:'rioL', kind:'knob', x:42, y:529, w:44, h:44, reverse:true,
    name:'V/UHF FUNCTION', states:['off','tr','trg','adf'],
    lab:{off:'OFF',tr:'T/R',trg:'T/R +G',adf:'ADF'}, init:'off' },
  { id:'rioTacanFunc', view:'rioL', kind:'knob', x:222, y:679, w:60, h:60, reverse:true,
    name:'RIO TACAN FUNCTION', states:['off','rec','tr','aa','bcn'],
    lab:{off:'OFF',rec:'REC',tr:'T/R',aa:'A/A',bcn:'BCN'}, init:'off' },

  /* ================= RIO · centre panel =================================== */
  { id:'navMode', view:'rioC', kind:'knob', x:712, y:465, w:64, h:64,
    name:'NAV MODE SELECTOR', states:['off','gnd','align','cva','ins','cat','ahrs'],
    lab:{off:'OFF',gnd:'GND ALIGN',align:'ALIGN',cva:'CVA',ins:'INS',cat:'CAT',ahrs:'AHRS'}, init:'off' },
  { id:'rioStbyAdi', view:'rioC', kind:'knob', x:320, y:440, w:64, h:64,
    name:'RIO STANDBY ADI (est)', states:['caged','erect'], lab:{caged:'CAGED',erect:'ERECT'}, init:'caged' },

  /* ================= RIO · right console ================================== */
  { id:'irtvPower', view:'rioR', kind:'sw', x:476, y:760, w:36, h:64,
    name:'IR / TV (TCS) POWER (est)', states:['off','stby','on'],
    lab:{off:'OFF',stby:'STBY',on:'ON'}, init:'off' },
  { id:'wcsMode', view:'rioR', kind:'sw', x:698, y:766, w:40, h:64,
    name:'WCS MODE', states:['off','stby','xmt'],
    lab:{off:'OFF',stby:'STBY',xmt:'WCS XMT'}, init:'off' },
  { id:'alr67Power', view:'rioR', kind:'sw', x:1486, y:127, w:36, h:44,
    name:'ALR-67 RWR POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'decmMode', view:'rioR', kind:'knob', x:1384, y:274, w:72, h:72,
    name:'ALQ-126 DECM MODE', states:['off','stby','rec','rpt','act'],
    lab:{off:'OFF',stby:'STBY',rec:'REC',rpt:'RPT',act:'ACT'}, init:'off' },
  { id:'ale39Mode', view:'rioR', kind:'sw', x:1508, y:488, w:36, h:70,
    name:'ALE-39 PWR / MODE (est)', states:['off','man','auto'],
    lab:{off:'OFF',man:'MAN',auto:'AUTO (CHAFF)'}, init:'off' },
  { id:'flareMode', view:'rioR', kind:'sw', x:1338, y:606, w:36, h:60,
    name:'FLARE MODE', states:['pilot','norm','mult'],
    lab:{pilot:'PILOT',norm:'NORM',mult:'MULT'}, init:'norm' },
  { id:'dlPower', view:'rioR', kind:'sw', x:1631, y:406, w:36, h:44,
    name:'DATALINK POWER (est)', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'dlModeSw', view:'rioR', kind:'sw', x:1839, y:352, w:36, h:44,
    name:'DATALINK MODE (est)', states:['tac','cains'],
    lab:{tac:'TAC',cains:'CAINS / WAYPT'}, init:'tac' },
  { id:'iffMode4', view:'rioR', kind:'sw', x:1621, y:845, w:36, h:48,
    name:'IFF MODE 4 POWER (est)', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
];

/* the CAP number keys are dual purpose: first press picks the field, then digits */
function capKey(id, x, y, name) {
  return [{ id, view:'rioL', kind:'push', x, y, w:42, h:32, name,
            states:['out','in'], lab:{out:name.split(' · ')[0], in:name[0]}, init:'out' }];
}
