/* ============================================================
   F-14B · CONTROLS
   Coordinates are pixels in the 1920x1080 space of each photo.
   Positions below were verified in Calibrate mode against the photos.

   view    'front' | 'consoles'      pilot
           'pilotBoth'               the centre panel, in both pilot photos
           'rioL' | 'rioC' | 'rioR'  RIO
           tray:true                 not visible in any photo
   states  listed bottom-to-top, so a left-click moves the switch
           up / forward. updir:false where the panel reads the other way.
   ============================================================ */

export const controls = [

  /* ================= PILOT · armament panel (in both pilot photos) ========= */
  { id:'gunRate', view:'pilotBoth', kind:'sw', x:874, y:48, w:36, h:44,
    name:'GUN RATE', states:['low','high'], lab:{high:'HIGH',low:'LOW'}, init:'low' },
  { id:'swCool', view:'pilotBoth', kind:'sw', x:942, y:47, w:34, h:46,
    name:'SW COOL', states:['off','on'], lab:{on:'ON',off:'OFF'}, init:'off' },
  { id:'mslPrep', view:'pilotBoth', kind:'sw', x:1011, y:46, w:34, h:46,
    name:'MSL PREP', states:['off','on'], lab:{on:'ON',off:'OFF'}, init:'off' },
  { id:'masterArm', view:'pilotBoth', kind:'lever', x:1174, y:16, w:46, h:98,
    name:'MASTER ARM', states:['tng','off','on'], lab:{on:'ON',off:'OFF',tng:'TNG'}, init:'off' },
  { id:'modeStp', view:'pilotBoth', kind:'sw', x:1107, y:132, w:45, h:41,
    name:'MISSILE MODE/STP', states:['brsit','norm'], lab:{norm:'NORM',brsit:'BRSIT'}, init:'norm' },
  { id:'masterCaution', view:'pilotBoth', kind:'lamp', x:919, y:118, w:85, h:21,
    name:'MASTER CAUTION', color:'amber', watch:'masterCaution' },

  /* ================= PILOT · front panel ================================== */
  { id:'parkBrake', view:'front', kind:'lever', x:22, y:857, w:102, h:88, updir:false,
    name:'PARKING BRAKE', states:['off','set'], lab:{off:'RELEASED',set:'ENGAGED'}, init:'set' },
  { id:'gearHandle', view:'front', kind:'lever', x:210, y:738, w:46, h:60,
    name:'LANDING GEAR', states:['down','up'], lab:{down:'DOWN',up:'UP'}, init:'down' },
  { id:'radAltKnob', view:'front', kind:'knob', x:236, y:583, w:34, h:34,
    name:'RADAR ALTIMETER', states:['off','on'], lab:{off:'OFF',on:'BIT'}, init:'off' },
  { id:'stbyAdi', view:'front', kind:'knob', x:1371, y:389, w:38, h:38,
    name:'STANDBY ADI CAGE', states:['caged','erect'], lab:{caged:'CAGED',erect:'ERECT'}, init:'caged' },
  { id:'antiSkid', view:'front', kind:'sw', x:614, y:1013, w:36, h:48,
    name:'ANTI-SKID / SPOILER BK', states:['spoiler','off','both'],
    lab:{both:'BOTH',off:'OFF',spoiler:'SPLR BK'}, init:'both' },
  { id:'wingExtTrans', view:'front', kind:'sw', x:260, y:1013, w:36, h:52,
    name:'WING/EXT TRANS', states:['off','auto','oride'],
    lab:{oride:'ORIDE',auto:'AUTO',off:'OFF'}, init:'auto' },
  // ---- landing configuration ----
  { id:'hookHandle', view:'front', kind:'lever', x:1659, y:626, w:40, h:74, updir:false,
    name:'ARRESTING HOOK', states:['up','down'], lab:{up:'UP',down:'DOWN'}, init:'up' },
  { id:'altBaro', view:'front', kind:'knob', x:440, y:579, w:34, h:34,
    name:'ALTIMETER BARO SET', states:['set','turn'], lab:{set:'—',turn:'SET'}, init:'set' },
  { id:'masterReset', view:'front', kind:'push', x:684, y:1033, w:32, h:32,
    name:'MASTER RESET', states:['out','in'], lab:{out:'—',in:'PRESSED'}, init:'out' },

  /* displays panel — the left column is the master mode buttons, not a mode knob */
  { id:'masterMode', view:'front', kind:'push', x:1651, y:764, w:38, h:184, stack:'v',
    name:'DISPLAY MASTER MODE', states:['to','cruise','aa','ag','ldg'],
    lab:{to:'T.O.',cruise:'CRUISE',aa:'A/A',ag:'A/G',ldg:'LDG'}, init:'to' },
  { id:'hudDeclutter', view:'front', kind:'sw', x:1713, y:781, w:36, h:34,
    name:'HUD DECLUTTER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hudAwl', view:'front', kind:'sw', x:1778, y:788, w:36, h:34,
    name:'HUD AWL MODE', states:['acl','ils'], lab:{ils:'ILS',acl:'ACL'}, init:'ils' },
  { id:'vdiMode', view:'front', kind:'sw', x:1711, y:840, w:36, h:34,
    name:'VDI MODE', states:['norm','tv'], lab:{norm:'NORM',tv:'TV'}, init:'norm' },
  { id:'vdiAwl', view:'front', kind:'sw', x:1779, y:854, w:36, h:34,
    name:'VDI AWL MODE', states:['acl','ils'], lab:{ils:'ILS',acl:'ACL'}, init:'ils' },
  { id:'hsdMode', view:'front', kind:'sw', x:1712, y:893, w:36, h:34,
    name:'HSD MODE', states:['tid','nav'], lab:{nav:'NAV',tid:'TID'}, init:'nav' },
  { id:'hsdEcm', view:'front', kind:'sw', x:1780, y:907, w:36, h:28,
    name:'HSD ECM', states:['off','oride'], lab:{oride:'ORIDE',off:'OFF'}, init:'off' },
  { id:'vdiPower', view:'front', kind:'sw', x:1649, y:951, w:36, h:48,
    name:'VDI POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hudPower', view:'front', kind:'sw', x:1714, y:948, w:36, h:48,
    name:'HUD POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  /* Gunsight elevation lead, just right of the display power switches and above
     the STEER CMD row. Position mapped from a zoom against those three switches. */
  { id:'gunLead', view:'front', kind:'knob', x:1845, y:964, w:36, h:36,
    name:'GUNSIGHT ELEVATION LEAD (mils)',
    states:['000','025','050','075','100'],
    lab:{'000':'000','025':'025','050':'050','075':'075','100':'100'}, init:'050' },
  { id:'hsdPower', view:'front', kind:'sw', x:1781, y:948, w:36, h:48,
    name:'HSD POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },

  /* ================= PILOT · consoles ===================================== */
  // the pale FLAP block inboard of the left throttle — measured 56x97 at (332,162)
  { id:'flapsLever', view:'consoles', kind:'lever', x:303, y:112, w:58, h:101, updir:false,
    name:'SLATS / FLAPS', states:['up','down'], lab:{up:'UP',down:'DOWN'}, init:'up' },
  { id:'throttleL', view:'consoles', kind:'lever', x:396, y:150, w:46, h:170,
    name:'LEFT THROTTLE', states:['off','idle','half','mil'],
    lab:{off:'CUTOFF',idle:'IDLE',half:'HALF',mil:'MIL'}, init:'off' },
  { id:'throttleR', view:'consoles', kind:'lever', x:450, y:150, w:46, h:170,
    name:'RIGHT THROTTLE', states:['off','idle','half','mil'],
    lab:{off:'CUTOFF',idle:'IDLE',half:'HALF',mil:'MIL'}, init:'off' },
  { id:'wingSweep', view:'consoles', kind:'lever', x:572, y:100, w:28, h:252,
    name:'EMERG WING SWEEP HANDLE', states:['oversweep','fwd','detent'],
    lab:{oversweep:'OVERSWEEP 68°',fwd:'FWD 20° (raised)',detent:'FWD 20° · IN DETENT'},
    init:'oversweep' },
  { id:'engCrank', view:'consoles', kind:'sw', axis:'x', x:99, y:132, w:76, h:34,
    name:'ENGINE CRANK', states:['left','off','right'],
    lab:{left:'L',off:'OFF',right:'R'}, init:'off', spring:true },
  { id:'oxygen', view:'consoles', kind:'sw', x:540, y:980, w:38, h:50,
    name:'OXYGEN', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'ics', view:'consoles', kind:'sw', x:289, y:783, w:36, h:54,
    name:'ICS (INTERCOM)', states:['cold','hot','ovrd'],
    lab:{cold:'COLD MIC',hot:'HOT MIC',ovrd:'RADIO OVERRIDE'}, init:'cold' },
  { id:'afcsPitch', view:'consoles', kind:'sw', x:93, y:543, w:34, h:58,
    name:'SAS PITCH', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'afcsRoll', view:'consoles', kind:'sw', x:178, y:543, w:34, h:58,
    name:'SAS ROLL', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'afcsYaw', view:'consoles', kind:'sw', x:261, y:543, w:34, h:58,
    name:'SAS YAW', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  // four detents, not three — ADF was missing. Angles measured off the legends.
  { id:'uhfFunc', view:'consoles', kind:'knob', x:594, y:614, w:46, h:48, reverse:true,
    name:'UHF 1 FUNCTION (ARC-159)', states:['off','main','both','adf'],
    lab:{off:'OFF',main:'MAIN',both:'BOTH',adf:'ADF'},
    angles:[-135, -106, -86, -63], init:'off' },
  { id:'tacanFunc', view:'consoles', kind:'knob', x:588, y:810, w:52, h:60, reverse:true,
    name:'TACAN FUNCTION', states:['off','rec','tr','aa','bcn'],
    lab:{off:'OFF',rec:'REC',tr:'T/R',aa:'A/A',bcn:'BCN'}, init:'off' },
  { id:'masterGenL', view:'consoles', kind:'sw', x:1311, y:515, w:36, h:52,
    name:'L MASTER GEN', states:['test','off','norm'],
    lab:{norm:'NORM',off:'OFF/RST',test:'TEST'}, init:'norm' },
  { id:'masterGenR', view:'consoles', kind:'sw', x:1391, y:515, w:36, h:52,
    name:'R MASTER GEN', states:['test','off','norm'],
    lab:{norm:'NORM',off:'OFF/RST',test:'TEST'}, init:'norm' },
  { id:'airSource', view:'consoles', kind:'push', x:1502, y:638, w:40, h:208, stack:'v',
    name:'AIR SOURCE', states:['ram','leng','reng','both','off'],
    lab:{ram:'RAM',leng:'L ENG',reng:'R ENG',both:'BOTH ENG',off:'OFF'}, init:'off' },
  { id:'hydTransfer', view:'consoles', kind:'lever', x:1399, y:974, w:36, h:92, updir:false,
    name:'HYD TRANSFER PUMP', states:['shutoff','norm'],
    lab:{norm:'NORM',shutoff:'SHUTOFF'}, init:'norm' },
  { id:'emergFltHyd', view:'consoles', kind:'lever', x:1851, y:855, w:36, h:106,
    name:'EMERG FLIGHT HYD', states:['autolow','low','high'],
    lab:{autolow:'AUTO / LOW',low:'LOW',high:'HIGH'}, init:'autolow' },
  { id:'ara63', view:'consoles', kind:'sw', x:1830, y:327, w:36, h:42,
    name:'ARA-63 ICLS POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'hookBypass', view:'consoles', kind:'sw', x:1834, y:476, w:36, h:46,
    name:'HOOK BYPASS', states:['carrier','field'],
    lab:{field:'FIELD',carrier:'CARRIER'}, init:'field' },
  { id:'landingLights', view:'consoles', kind:'sw', x:1826, y:554, w:36, h:46,
    name:'LANDING / TAXI LIGHTS', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  { id:'extLights', view:'consoles', kind:'sw', x:1650, y:464, w:32, h:44,
    name:'POSITION LIGHTS', states:['dim','off','brt'],
    lab:{dim:'DIM',off:'OFF',brt:'BRT'}, init:'off' },

  /* caution / advisory capsules. 4 columns at 1348.5/1412.5/1477/1541.5,
     13 caption rows starting at y=188 with roughly 20px pitch. */
  { id:'clStartValve', view:'consoles', kind:'lamp', x:1511, y:220, w:61, h:17,
    name:'START VALVE', color:'amber', watch:'startValve' },
  { id:'clOilPress', view:'consoles', kind:'lamp', x:1446, y:259, w:61, h:17,
    name:'OIL PRESS', color:'red', watch:'oilPress' },
  { id:'clLGen', view:'consoles', kind:'lamp', x:1318, y:298, w:61, h:17,
    name:'L GEN', color:'amber', watch:'lGen' },
  { id:'clRGen', view:'consoles', kind:'lamp', x:1382, y:298, w:61, h:17,
    name:'R GEN', color:'amber', watch:'rGen' },
  { id:'clCanopy', view:'consoles', kind:'lamp', x:1446, y:298, w:61, h:17,
    name:'CANOPY', color:'amber', watch:'canopy' },
  { id:'clHydPress', view:'consoles', kind:'lamp', x:1511, y:321, w:61, h:17,
    name:'HYD PRESS', color:'amber', watch:'hydPress' },

  /* ================= not visible in any photo ============================= */
  { id:'designate', tray:true, kind:'lever', name:'DESIGNATE HOOKED TRACK (HCU)',
    states:['friendly','unknown','hostile'],
    lab:{hostile:'HOSTILE', unknown:'UNKNOWN', friendly:'FRIENDLY'}, init:'unknown' },
  { id:'noAttack', tray:true, kind:'lever', name:'DO NOT ATTACK (hooked track)',
    states:['clear','set'], lab:{clear:'\u2014', set:'APPLY'}, init:'clear' },
  { id:'radarMode', tray:true, kind:'lever', name:'WCS MODE (selected)',
    states:['pulsesrch','pdsrch','rws','twsman','twsauto','pulsestt','pdstt'],
    lab:{pulsesrch:'PULSE SRCH', pdsrch:'PD SRCH', rws:'RWS', twsman:'TWS MAN',
         twsauto:'TWS AUTO', pulsestt:'PULSE STT', pdstt:'PD STT'}, init:'pdsrch' },
  { id:'weaponSel', tray:true, kind:'lever', name:'WEAPON SELECTOR (throttle)',
    states:['gun','sw','sp','ph'],
    lab:{gun:'GUN', sw:'SW \u00b7 Sidewinder', sp:'SP \u00b7 Sparrow', ph:'PH \u00b7 Phoenix'}, init:'gun' },
  { id:'trigger', tray:true, kind:'lever', name:'TRIGGER, SECOND STAGE (stick)',
    states:['off','fire'], lab:{off:'\u2014', fire:'FIRE'}, init:'off' },
  { id:'cageSeam', tray:true, kind:'lever', name:'CAGE / SEAM (throttle)',
    states:['caged','seam'], lab:{caged:'CAGED', seam:'SEAM'}, init:'caged' },
  { id:'speedBrake', tray:true, kind:'lever', name:'SPEED BRAKE (throttle)',
    states:['in','out'], lab:{in:'IN',out:'OUT'}, init:'in' },
  { id:'dlc', tray:true, kind:'lever', name:'DLC THUMBWHEEL (stick)',
    states:['off','on'], lab:{off:'OFF',on:'ENGAGED'}, init:'off' },
  /* Left vertical console. Three positions, spring-loaded to OFF:
       KNEEL — releases strut pressure, retracts the strut and unlocks the launch bar
       OFF   — no strut movement
       EXTD  — extends the strut, raises and locks the launch bar
     In the tray because I have no measured position for it on the photos. */
      { id:'noseStrut', tray:true, kind:'sw', name:'NOSE STRUT',
    states:['kneel','off','extd'],
    lab:{ kneel:'KNEEL \u00b7 launch bar unlocked', off:'OFF', extd:'EXTD \u00b7 bar up and locked' },
    init:'off' },
  { id:'sweepThumb', tray:true, kind:'lever', name:'WING SWEEP THUMB SWITCH (stick)',
    states:['fwd','aft'], lab:{fwd:'FWD · 20°',aft:'AFT · 68°'}, init:'fwd' },
  { id:'ejectSeat', tray:true, kind:'lever', name:'EJECTION SEAT',
    states:['safe','armed'], lab:{safe:'SAFE',armed:'ARMED'}, init:'safe' },
  { id:'canopy', tray:true, kind:'lever', name:'CANOPY',
    states:['open','closed'], lab:{open:'OPEN',closed:'CLOSED'}, init:'open' },

  /* ================= RIO · left console =================================== */
  /* CAP keyboard. Grid taken from the printed legends: columns at
     398/444/492/540/588, rows at 101/145/192. */
  { id:'capClear', view:'rioL', kind:'push', ctx:'dgCap_rioL', x:380, y:90, w:44, h:30,
    name:'CAP CLEAR', states:['out','in'], lab:{out:'CLEAR',in:'CLEAR'}, init:'out' },
  { id:'capSW', view:'rioL', kind:'push', ctx:'dgCap_rioL', x:455, y:88, w:32, h:30,
    name:'CAP S / W', states:['out','in'], lab:{out:'S-W',in:'S-W'}, init:'out' },
  { id:'capNE', view:'rioL', kind:'push', ctx:'dgCap_rioL', x:508, y:88, w:32, h:30,
    name:'CAP N / E', states:['out','in'], lab:{out:'N-E',in:'N-E'}, init:'out' },
  { id:'capEnter', view:'rioL', kind:'push', ctx:'dgCap_rioL', x:568, y:88, w:48, h:30,
    name:'CAP ENTER', states:['out','in'], lab:{out:'ENTER',in:'ENTER'}, init:'out' },
  ...capKey('cap1', 375, 132, '1 · LAT'),  ...capKey('cap2', 423, 132, '2 · NPR'),
  ...capKey('cap3', 471, 132, '3 · SPD'),  ...capKey('cap4', 520, 132, '4 · ALT'),
  ...capKey('cap5', 569, 133, '5 · RNG'),  ...capKey('cap6', 377, 177, '6 · LONG'),
  ...capKey('cap7', 426, 178, '7'),        ...capKey('cap8', 475, 180, '8 · HDG'),
  ...capKey('cap9', 523, 178, '9'),        ...capKey('cap0', 571, 179, '0 · BRG'),

  /* CAP message select buttons — two columns of five, Hough-measured */
  { id:'msgOwnAC', view:'rioL', kind:'lamp', x:358, y:254, w:32, h:32,
    name:'OWN A/C', color:'green', watch:'msgOwnAC' },
  { id:'msgStoredHdg', view:'rioL', kind:'lamp', x:360, y:290, w:32, h:32,
    name:'STORED HDG ALIGN', color:'green', watch:'none' },
  { id:'msgTarpsNav', view:'rioL', kind:'lamp', x:357, y:331, w:32, h:32,
    name:'TARPS NAV FIX', color:'green', watch:'none' },
  { id:'msgWindSpd', view:'rioL', kind:'lamp', x:359, y:368, w:32, h:32,
    name:'WIND SPD HDG', color:'green', watch:'none' },
  { id:'msgTarps', view:'rioL', kind:'lamp', x:360, y:404, w:32, h:32,
    name:'TARPS', color:'green', watch:'none' },
  { id:'msgTacanFix', view:'rioL', kind:'lamp', x:595, y:263, w:32, h:32,
    name:'TACAN FIX', color:'green', watch:'none' },
  { id:'msgRdrFix', view:'rioL', kind:'lamp', x:595, y:296, w:32, h:32,
    name:'RDR FIX', color:'green', watch:'none' },
  { id:'msgVisFix', view:'rioL', kind:'lamp', x:596, y:333, w:32, h:32,
    name:'VIS FIX', color:'green', watch:'none' },
  { id:'msgFixEnable', view:'rioL', kind:'lamp', x:595, y:367, w:32, h:32,
    name:'FIX ENABLE', color:'green', watch:'none' },
  { id:'msgMagVar', view:'rioL', kind:'push', ctx:'dgCap_rioL', x:595, y:404, w:32, h:32,
    name:'MAG VAR HDG', watch:'msgMagVar', states:['out','in'], lab:{out:'MAG VAR',in:'MAG VAR'}, init:'out' },

  { id:'capCategory', view:'rioL', kind:'knob', x:467, y:472, w:56, h:56, reverse:true,
    name:'CAP CATEGORY', states:['bit','spl','nav','tacdata','dl','tgtdata'],
    lab:{bit:'BIT',spl:'SPL',nav:'NAV',tacdata:'TAC DATA',dl:'D/L',tgtdata:'TGT DATA'}, init:'nav' },
  // sits hard against the left edge of the photo; the -1 is deliberate
  { id:'liquidCool', view:'rioL', kind:'sw', x:-1, y:280, w:34, h:52,
    // forward is AWG-9/AIM-54, aft is AWG-9 alone. Last in the list is forward.
    name:'LIQUID COOLING', states:['awg9','off','awg9aim54'],
    lab:{awg9:'AWG-9',off:'OFF',awg9aim54:'AWG-9 / AIM-54'}, init:'off' },
  { id:'rioIcs', view:'rioL', kind:'sw', x:595, y:745, w:34, h:58,
    name:'RIO ICS', states:['cold','hot','ovrd'],
    lab:{cold:'COLD MIC',hot:'HOT MIC',ovrd:'RADIO OVERRIDE'}, init:'cold' },
  { id:'rioOxygen', view:'rioL', kind:'sw', x:403, y:997, w:32, h:44,
    name:'RIO OXYGEN', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  // (est) the MODE knob, right of the channel select — worth a Calibrate pass
  { id:'vuhfFunc', view:'rioL', kind:'knob', x:233, y:529, w:46, h:46, reverse:true,
    name:'V/UHF MODE', states:['off','tr','trg','adf'],
    lab:{off:'OFF',tr:'T/R',trg:'T/R +G',adf:'ADF'}, init:'off' },
  { id:'rioTacanFunc', view:'rioL', kind:'knob', x:223, y:680, w:60, h:60, reverse:true,
    name:'RIO TACAN FUNCTION', states:['off','rec','tr','aa','bcn'],
    lab:{off:'OFF',rec:'REC',tr:'T/R',aa:'A/A',bcn:'BCN'}, init:'off' },

  /* ---- radar and weapons control, for BVR. All (est): the WCS MODE cluster
     and the weapons panel did not detect cleanly, so these want a Calibrate pass. ---- */
  /* WCS MODE — seven momentary buttons, measured off the panel. Each selects
     a mode on radarMode, which holds the state and reads it out in the tray. */
  { id:'rm_pdstt', view:'rioL', kind:'push', x:1183, y:243, w:34, h:30,
    name:'WCS MODE \u00b7 PD STT', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'pdstt' }, watch:s=>s.sw.radarMode==='pdstt' },
  { id:'rm_pulsestt', view:'rioL', kind:'push', x:1220, y:243, w:34, h:30,
    name:'WCS MODE \u00b7 PULSE STT', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'pulsestt' }, watch:s=>s.sw.radarMode==='pulsestt' },
  { id:'rm_pdsrch', view:'rioL', kind:'push', x:1262, y:243, w:34, h:30,
    name:'WCS MODE \u00b7 PD SRCH', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'pdsrch' }, watch:s=>s.sw.radarMode==='pdsrch' },
  { id:'rm_rws', view:'rioL', kind:'push', x:1303, y:243, w:34, h:30,
    name:'WCS MODE \u00b7 RWS', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'rws' }, watch:s=>s.sw.radarMode==='rws' },
  { id:'rm_twsauto', view:'rioL', kind:'push', x:1271, y:288, w:34, h:30,
    name:'WCS MODE \u00b7 TWS AUTO', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'twsauto' }, watch:s=>s.sw.radarMode==='twsauto' },
  { id:'rm_twsman', view:'rioL', kind:'push', x:1309, y:288, w:34, h:30,
    name:'WCS MODE \u00b7 TWS MAN', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'twsman' }, watch:s=>s.sw.radarMode==='twsman' },
  { id:'rm_pulsesrch', view:'rioL', kind:'push', x:1350, y:288, w:34, h:30,
    name:'WCS MODE \u00b7 PULSE SRCH', states:['out'], lab:{out:'SELECT'}, init:'out',
    sets:{ id:'radarMode', value:'pulsesrch' }, watch:s=>s.sw.radarMode==='pulsesrch' },
  { id:'azScan', view:'rioL', kind:'knob', x:120, y:115, w:60, h:60,
    name:'AZ SCAN (est)', states:['10','20','40','65'],
    lab:{'10':'±10°','20':'±20°','40':'±40°','65':'±65°'}, init:'40' },
  { id:'elBars', view:'rioL', kind:'knob', x:210, y:115, w:60, h:60,
    name:'EL BARS (est)', states:['1','2','4','8'],
    lab:{'1':'1 BAR','2':'2 BAR','4':'4 BAR','8':'8 BAR'}, init:'2' },
  { id:'tgtSize', view:'rioR', kind:'sw', x:560, y:24, w:36, h:56,
    name:'TGTS SIZE (est)', states:['small','norm','large'],
    lab:{small:'SMALL · pitbull 6 nm', norm:'NORM · pitbull 10 nm', large:'LARGE · pitbull 13 nm'},
    init:'norm' },
  /* A/A OPTIONS and MSL SPD GATE, measured against the LAUNCH button.
     The gate is a six position rotary, not a toggle. */
  { id:'mslOptions', view:'rioR', kind:'sw', x:244, y:1015, w:28, h:44,
    name:'A/A OPTIONS', states:['phact','norm','sppd'],
    lab:{sppd:'SP PD', norm:'NORM · SARH then active', phact:'PH ACT · active off the rail'},
    init:'norm' },
  { id:'mslGate', view:'rioR', kind:'knob', x:309, y:1021, w:58, h:58,
    name:'MSL SPD GATE',
    states:['wide','var','nose','noseqtr','tailqtr','tail'],
    lab:{wide:'WIDE', var:'VAR', nose:'NOSE', noseqtr:'NOSE QTR', tailqtr:'TAIL QTR', tail:'TAIL'},
    angles:[0, 45, 68, 96, 120, 144], init:'wide' },
  { id:'nextLaunch', view:'rioR', kind:'push', x:180, y:1005, w:44, h:32,
    name:'NEXT LAUNCH', states:['out','in'], lab:{out:'NEXT LAUNCH',in:'\u2014'}, init:'out' },
  { id:'launchBtn', view:'rioR', kind:'push', x:326, y:928, w:60, h:60,
    name:'A/A LAUNCH', states:['out','in'], lab:{out:'LAUNCH',in:'FIRING'}, init:'out' },

  /* ================= RIO · centre panel =================================== */
  { id:'lampStby', view:'rioC', kind:'lamp', x:714, y:422, w:54, h:16,
    name:'STBY', color:'green', watch:'stbyLight' },
  { id:'lampReady', view:'rioC', kind:'lamp', x:713, y:440, w:54, h:16,
    name:'READY', color:'green', watch:'readyLight' },
  { id:'navMode', view:'rioC', kind:'knob', x:732, y:486, w:64, h:64, reverse:true,
    name:'NAV MODE SELECTOR', states:['off','gnd','cva','cat','ins','ahrs','imu'],
    lab:{off:'OFF',gnd:'GND ALIGN',cva:'CVA',cat:'CAT',ins:'INS',ahrs:'AHRS',imu:'IMU/AM'}, init:'off' },
  // The standby attitude gauge, identified by the only horizon on this panel:
  // its face splits bright-over-dark (+102) where the airspeed and altimeter
  // dials next to it read +14 and -3. The cage knob is too small to isolate at
  // this resolution, so the hotspot sits on the instrument itself.
  { id:'rioStbyAdi', view:'rioC', kind:'knob', x:425, y:361, w:60, h:60,
    name:'RIO STANDBY ADI', states:['caged','erect'], lab:{caged:'CAGED',erect:'ERECT'}, init:'caged' },

  /* ================= RIO · right console ================================== */
  { id:'irtvPower', view:'rioR', kind:'sw', x:477, y:755, w:36, h:64, reverse:true,
    name:'IR / TV (TCS) POWER', states:['off','stby','on'],
    lab:{off:'OFF',stby:'STBY',on:'ON'}, init:'off' },
  { id:'wcsMode', view:'rioR', kind:'sw', x:700, y:769, w:40, h:64, reverse:true,
    name:'WCS MODE', states:['off','stby','xmt'],
    lab:{off:'OFF',stby:'STBY',xmt:'WCS XMT'}, init:'off' },
  { id:'alr67Power', view:'rioR', kind:'sw', x:1485, y:139, w:36, h:44,
    name:'ALR-67 RWR POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
  // detent angles measured off the printed labels, 0 = up, clockwise positive
  { id:'decmMode', view:'rioR', kind:'knob', x:1384, y:274, w:72, h:72, reverse:true,
    name:'ALQ-126 DECM MODE', states:['off','stby','hold','act','rec','rpt'],
    lab:{off:'OFF',stby:'STBY',hold:'HOLD 3 SEC',act:'ACT',rec:'REC',rpt:'RPT'},
    angles:[-108, -81, -53, -30, 31, 54], init:'off' },
  { id:'ale39Mode', view:'rioR', kind:'sw', x:1505, y:493, w:36, h:70, reverse:true,
    name:'ALE-39 PWR / MODE', states:['off','man','auto'],
    lab:{off:'OFF',man:'MAN',auto:'AUTO (CHAFF)'}, init:'off' },
  { id:'flareMode', view:'rioR', kind:'sw', x:1336, y:607, w:36, h:60, reverse:true,
    name:'FLARE MODE', states:['pilot','norm','mult'],
    lab:{pilot:'PILOT',norm:'NORM',mult:'MULT'}, init:'pilot' },
  // (est) forward of the datalink mode switch — worth a Calibrate pass
  { id:'dlPower', view:'rioR', kind:'sw', x:1852, y:228, w:36, h:52,
    name:'DATALINK POWER', states:['aux','off','on'],
    lab:{on:'ON · LINK 4A', off:'OFF', aux:'AUX · LINK 4C'}, init:'off' },
  // (est) REPLY and ADDRESS on the same panel — worth a Calibrate pass
  { id:'dlReply', view:'rioR', kind:'sw', x:1747, y:354, w:36, h:44,
    name:'DATALINK REPLY', states:['canc','norm'],
    lab:{norm:'NORM', canc:'CANC'}, init:'norm' },
  { id:'dlAddress', view:'rioR', kind:'knob', x:1834, y:404, w:50, h:36,
    name:'DATALINK ADDRESS', states:['01','02','03','04'],
    lab:{'01':'01 · lead','02':'02 · wing','03':'03 · elem lead','04':'04 · elem wing'}, init:'01' },
  { id:'dlModeSw', view:'rioR', kind:'sw', x:1840, y:336, w:36, h:44,
    name:'DATALINK MODE', states:['tac','cains'],
    lab:{tac:'TAC',cains:'CAINS / WAYPT'}, init:'tac' },
  { id:'dlFreq', view:'rioR', kind:'knob', x:1718, y:232, w:90, h:62,
    name:'DATALINK FREQ WHEELS', states:['000','092','184','209','240'],
    lab:{'000':'0 0 0', '092':'09.2 · E-2C', '184':'18.4 · E-2C alt',
         '209':'20.9 · CVN-74', '240':'24.0 · flight'}, init:'000' },
  { id:'iffMode4', view:'rioR', kind:'sw', x:1621, y:836, w:36, h:48,
    name:'IFF MODE 4 POWER', states:['off','on'], lab:{off:'OFF',on:'ON'}, init:'off' },
];

/* the CAP number keys are dual purpose: first press picks the field, then digits */
function capKey(id, x, y, name) {
  return [{ id, view:'rioL', kind:'push', x, y, w:42, h:32, name, ctx:'dgCap_rioL',
            states:['out','in'], lab:{out:name.split(' · ')[0], in:name[0]}, init:'out' }];
}
